"""Coding-pool backend definitions: third party."""

import os

BACKENDS = {
    "google_flash_code": {
        "url": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
        "key": os.environ.get("GOOGLE_AI_KEY", ""),
        "model": "gemini-2.5-flash",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "aliyun_qwen3_code": {
        "url": "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
        "key": os.environ.get("ALIYUN_API_KEY", ""),
        "model": "qwen3-8b",
        "fmt": "openai",
        "timeout": 20,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
    },
    "xfyun_astron": {
        "url": "https://maas-coding-api.cn-huabei-1.xf-yun.com/v2/chat/completions",
        "key": os.environ.get("XFYUN_API_KEY", ""),
        "model": "astron-code-latest",
        "fmt": "openai",
        "timeout": 30,
        "auth": "bearer",
        "caps": ["tool_calls"],
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
    },
    "dashscope_coding": {
        "url": "https://coding.dashscope.aliyuncs.com/v1/chat/completions",
        "key": os.environ.get("DASHSCOPE_CODING_KEY", ""),
        "model": "qwen3-coder-plus",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "zhihu_zhida": {
        "url": "https://developer.zhihu.com/v1/chat/completions",
        "key": os.environ.get("ZHIHU_API_KEY", ""),
        "model": "zhida-fast-1p5",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
        "extra_headers": {"X-Request-Timestamp": "dynamic"},
    },
    "zhihu_zhida_think": {
        "url": "https://developer.zhihu.com/v1/chat/completions",
        "key": os.environ.get("ZHIHU_API_KEY", ""),
        "model": "zhida-thinking-1p5",
        "fmt": "openai",
        "timeout": 60,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "extra_headers": {"X-Request-Timestamp": "dynamic"},
    },
    "scnet_qwen235b_code": {
        "url": f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4505/v1/chat/completions",
        "key": "none",
        "model": "qwen3-235b",
        "fmt": "openai",
        "timeout": 60,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "scnet_ds_pro_code": {
        "url": f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4505/v1/chat/completions",
        "key": "none",
        "model": "deepseek-v4-pro",
        "fmt": "openai",
        "timeout": 90,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "or_gptoss_120b_code": {
        "url": "https://openrouter.ai/api/v1/chat/completions",
        "key": os.environ.get("OPENROUTER_API_KEY", ""),
        "model": "openai/gpt-oss-120b:free",
        "fmt": "openai",
        "timeout": 60,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "cfai_qwen_coder_code": {
        "url": f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions",
        "key": os.environ.get("CLOUDFLARE_TOKEN", ""),
        "model": "@cf/qwen/qwen2.5-coder-32b-instruct",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mistral_large_code": {
        "url": "https://api.mistral.ai/v1/chat/completions",
        "key": os.environ.get("MISTRAL_API_KEY", ""),
        "model": "mistral-large-latest",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "github_gpt4o_code": {
        "url": "https://models.inference.ai.azure.com/chat/completions",
        "key": os.environ.get("GITHUB_TOKEN", ""),
        "model": "gpt-4o",
        "fmt": "openai",
        "timeout": 30,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_web_code": {
        "url": f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4507/v1/chat/completions",
        "key": "none",
        "model": "mimo-web",
        "fmt": "openai",
        "timeout": 60,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_web_think_code": {
        "url": f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4507/v1/chat/completions",
        "key": "none",
        "model": "mimo-web-think",
        "fmt": "openai",
        "timeout": 120,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_v2_5_pro_code": {
        "url": "https://token-plan-cn.xiaomimimo.com/v1/chat/completions",
        "key": os.environ.get("MIMO_V2_PRO_KEY", ""),
        "model": "mimo-v2.5-pro",
        "fmt": "openai",
        "timeout": 45,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_v2_pro_code": {
        "url": "https://token-plan-cn.xiaomimimo.com/v1/chat/completions",
        "key": os.environ.get("MIMO_V2_PRO_KEY", ""),
        "model": "mimo-v2-pro",
        "fmt": "openai",
        "timeout": 45,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_v2_5_code": {
        "url": "https://token-plan-cn.xiaomimimo.com/v1/chat/completions",
        "key": os.environ.get("MIMO_V2_PRO_KEY", ""),
        "model": "mimo-v2.5",
        "fmt": "openai",
        "timeout": 45,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "mimo_v2_omni_code": {
        "url": "https://token-plan-cn.xiaomimimo.com/v1/chat/completions",
        "key": os.environ.get("MIMO_V2_PRO_KEY", ""),
        "model": "mimo-v2-omni",
        "fmt": "openai",
        "timeout": 30,
        "force_stream_param": True,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "ogw_gpt5_codex_code": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5-codex",
        "fmt": "openai",
        "timeout": 60,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "ogw_claude_sonnet_code": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "anthropic/claude-sonnet-4-6",
        "fmt": "openai",
        "timeout": 45,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "ogw_deepseek_v4_code": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "deepseek/deepseek-v4-pro",
        "fmt": "openai",
        "timeout": 60,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
    "ogw_gpt5_nano_code": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5-nano",
        "fmt": "openai",
        "timeout": 15,
        "admission": "code_floor_candidate",
        "private_code_allowed": True,
    },
    "agnes20_code": {
        "url": "https://apihub.agnes-ai.com/v1/chat/completions",
        "key": os.environ.get("AGNES_AI_API_KEY", ""),
        "model": "agnes-2.0-flash",
        "fmt": "openai",
        "timeout": 45,
        "admission": "code_medium_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls", "code"],
    },
    "agnes15_code": {
        "url": "https://apihub.agnes-ai.com/v1/chat/completions",
        "key": os.environ.get("AGNES_AI_API_KEY", ""),
        "model": "agnes-1.5-flash",
        "fmt": "openai",
        "timeout": 20,
        "admission": "code_floor_candidate",
        "private_code_allowed": True,
        "caps": ["tool_calls"],
    },
}
