"""Backend provider registry (BACKENDS dict)."""
import os
from dotenv import load_dotenv

load_dotenv()

LM_URL = 'http://localhost:1234/v1/chat/completions'

# -- Backend Registry --
BACKENDS = {
    'longcat_lite': {'url': 'https://api.longcat.chat/anthropic/v1/messages', 'key': os.environ.get('LONGCAT_API_KEY', ''), 'model': 'LongCat-Flash-Lite', 'fmt': 'anthropic', 'auth': 'bearer'},
    'longcat_chat': {'url': 'https://api.longcat.chat/anthropic/v1/messages', 'key': os.environ.get('LONGCAT_API_KEY', ''), 'model': 'LongCat-Flash-Chat', 'fmt': 'anthropic', 'auth': 'bearer'},
    'longcat_thinking': {'url': 'https://api.longcat.chat/anthropic/v1/messages', 'key': os.environ.get('LONGCAT_API_KEY', ''), 'model': 'LongCat-Flash-Thinking-2601', 'fmt': 'anthropic', 'auth': 'bearer'},
    'longcat_omni': {'url': 'https://api.longcat.chat/anthropic/v1/messages', 'key': os.environ.get('LONGCAT_API_KEY', ''), 'model': 'LongCat-Flash-Omni-2603', 'fmt': 'anthropic', 'auth': 'bearer', 'no_system': True},
    'longcat': {'url': 'https://api.longcat.chat/anthropic/v1/messages', 'key': os.environ.get('LONGCAT_API_KEY', ''), 'model': 'LongCat-2.0-Preview', 'fmt': 'anthropic', 'auth': 'bearer'},
    'longcat_web': {'url': 'http://localhost:4506/v1/chat/completions', 'key': 'local', 'model': 'longcat-web', 'fmt': 'openai', 'timeout': 60, 'force_stream_param': True, 'admission': 'code_floor_candidate', 'private_code_allowed': True},
    'longcat_web_think': {'url': 'http://localhost:4506/v1/chat/completions', 'key': 'local', 'model': 'longcat-web-think', 'fmt': 'openai', 'timeout': 120, 'force_stream_param': True},
    'longcat_web_research': {'url': 'http://localhost:4506/v1/chat/completions', 'key': 'local', 'model': 'longcat-web-research', 'fmt': 'openai', 'timeout': 180, 'force_stream_param': True},
    'nvidia_nemotron': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'nvidia/llama-3.3-nemotron-super-49b-v1', 'fmt': 'openai'},
    'nvidia_llama70b': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'meta/llama-3.3-70b-instruct', 'fmt': 'openai'},
    'nvidia_qwen_coder': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'qwen/qwen3-coder-480b-a35b-instruct', 'fmt': 'openai'},
    'nvidia_llama4': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'meta/llama-4-maverick-17b-128e-instruct', 'fmt': 'openai'},
    'nvidia_mistral': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'mistralai/mistral-large-3-675b-instruct-2512', 'fmt': 'openai'},
    'nvidia_phi4': {'url': 'https://integrate.api.nvidia.com/v1/chat/completions', 'key': os.environ.get('NVIDIA_API_KEY', ''), 'model': 'microsoft/phi-4-mini-instruct', 'fmt': 'openai'},
    'chinamobile': {'url': 'https://maas.gd.chinamobile.com:36007/ai/uifm/open/v1/chat/completions', 'key': os.environ.get('CHINAMOBILE_API_KEY', ''), 'model': 'minimax-m25', 'fmt': 'openai'},
    'or_deepseek_r1': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'deepseek/deepseek-v4-flash:free', 'fmt': 'openai', 'timeout': 60},
    'or_qwen3_coder': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'qwen/qwen3-coder:free', 'fmt': 'openai', 'timeout': 60},
    'or_llama70b': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'meta-llama/llama-3.3-70b-instruct:free', 'fmt': 'openai', 'timeout': 45},
    'or_nemotron': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'nvidia/llama-3.3-nemotron-super-49b-v1:free', 'fmt': 'openai', 'timeout': 60},
    'or_qwen3_80b': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'qwen/qwen3-next-80b-a3b-instruct:free', 'fmt': 'openai', 'timeout': 30},
    'or_nemotron120b': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'nvidia/nemotron-3-super-120b-a12b:free', 'fmt': 'openai', 'timeout': 60},
    'or_gptoss_120b': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'openai/gpt-oss-120b:free', 'fmt': 'openai', 'timeout': 60},
    'or_glm45': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'z-ai/glm-4.5-air:free', 'fmt': 'openai', 'timeout': 30},
    'or_minimax': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'minimax/minimax-m2.5:free', 'fmt': 'openai', 'timeout': 30},
    'or_gemma4': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'google/gemma-4-31b-it:free', 'fmt': 'openai', 'timeout': 30},
    'unclose_hermes': {'url': 'https://hermes.ai.unturf.com/v1/chat/completions', 'key': 'none', 'model': 'adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic', 'fmt': 'openai', 'timeout': 15},
    'unclose_qwen': {'url': 'https://qwen.ai.unturf.com/v1/chat/completions', 'key': 'none', 'model': 'Qwen3.6-27B-UD-Q4_K_XL.gguf', 'fmt': 'openai', 'timeout': 30, 'extra_body': {'chat_template_kwargs': {'enable_thinking': False}}},
    'groq_llama70b': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'llama-3.3-70b-versatile', 'fmt': 'openai', 'timeout': 15},
    'groq_gptoss': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'openai/gpt-oss-120b', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'groq_gptoss_20b': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'openai/gpt-oss-20b', 'fmt': 'openai', 'timeout': 10, 'caps': ['tool_calls']},
    'groq_qwen32b': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'qwen/qwen3-32b', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'groq_llama4': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'meta-llama/llama-4-scout-17b-16e-instruct', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'groq_llama8b': {'url': 'https://api.groq.com/openai/v1/chat/completions', 'key': os.environ.get('GROQ_API_KEY', ''), 'model': 'llama-3.1-8b-instant', 'fmt': 'openai', 'timeout': 10, 'caps': ['tool_calls']},
    'cerebras_qwen235b': {'url': 'https://api.cerebras.ai/v1/chat/completions', 'key': os.environ.get('CEREBRAS_API_KEY', ''), 'model': 'qwen-3-235b-a22b-instruct-2507', 'fmt': 'openai', 'timeout': 30, 'caps': ['tool_calls']},
    'cerebras_llama8b': {'url': 'https://api.cerebras.ai/v1/chat/completions', 'key': os.environ.get('CEREBRAS_API_KEY', ''), 'model': 'llama3.1-8b', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'cerebras_gptoss': {'url': 'https://api.cerebras.ai/v1/chat/completions', 'key': os.environ.get('CEREBRAS_API_KEY', ''), 'model': 'gpt-oss-120b', 'fmt': 'openai', 'timeout': 20, 'caps': ['tool_calls']},
    'github_gpt4o': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'gpt-4o', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'github_gpt4o_mini': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'gpt-4o-mini', 'fmt': 'openai', 'timeout': 15, 'caps': ['tool_calls']},
    'github_gpt5': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'gpt-5', 'fmt': 'openai', 'timeout': 30},
    'github_o3_mini': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'o3-mini', 'fmt': 'openai', 'timeout': 30},
    'github_o4_mini': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'o4-mini', 'fmt': 'openai', 'timeout': 30},
    'github_deepseek_r1': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'DeepSeek-R1', 'fmt': 'openai', 'timeout': 60},
    'github_llama70b': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'Llama-3.3-70B-Instruct', 'fmt': 'openai', 'timeout': 15},
    'github_codestral': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'Codestral-2501', 'fmt': 'openai', 'timeout': 15},
    'google_flash_lite': {'url': 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', 'key': os.environ.get('GOOGLE_AI_KEY', ''), 'model': 'gemini-2.5-flash-lite', 'fmt': 'openai', 'timeout': 15},
    'google_flash': {'url': 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', 'key': os.environ.get('GOOGLE_AI_KEY', ''), 'model': 'gemini-2.5-flash', 'fmt': 'openai', 'timeout': 20},
    'google_pro': {'url': 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', 'key': os.environ.get('GOOGLE_AI_KEY', ''), 'model': 'gemini-2.5-pro', 'fmt': 'openai', 'timeout': 30},
    'cf_llama70b': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/meta/llama-3.3-70b-instruct-fp8-fast', 'fmt': 'openai', 'timeout': 15},
    'cf_llama4': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/meta/llama-4-scout-17b-16e-instruct', 'fmt': 'openai', 'timeout': 15},
    'cf_qwen_coder': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/qwen/qwen2.5-coder-32b-instruct', 'fmt': 'openai', 'timeout': 15},
    'cf_mistral': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/mistralai/mistral-small-3.1-24b-instruct', 'fmt': 'openai', 'timeout': 15},
    'cf_vision': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/meta/llama-3.2-11b-vision-instruct', 'fmt': 'openai', 'timeout': 15},
    # ── Cloudflare 新增 (37个模型嗅探, 挑最强) ──
    'cf_kimi_k26': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/moonshotai/kimi-k2.6', 'fmt': 'openai', 'timeout': 30},
    'cf_deepseek_r1': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', 'fmt': 'openai', 'timeout': 45},
    'cf_qwq': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/qwen/qwq-32b', 'fmt': 'openai', 'timeout': 45},
    'cf_gptoss_120b': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/openai/gpt-oss-120b', 'fmt': 'openai', 'timeout': 30},
    'cf_qwen3_30b': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/qwen/qwen3-30b-a3b-fp8', 'fmt': 'openai', 'timeout': 20},
    'cf_nemotron': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/nvidia/nemotron-3-120b-a12b', 'fmt': 'openai', 'timeout': 30},
    'cf_glm47': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/zai-org/glm-4.7-flash', 'fmt': 'openai', 'timeout': 15},
    'cf_gemma4': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/google/gemma-4-26b-a4b-it', 'fmt': 'openai', 'timeout': 20},
    'mistral_large': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'mistral-large-latest', 'fmt': 'openai', 'timeout': 20},
    'mistral_small': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'mistral-small-latest', 'fmt': 'openai', 'timeout': 15},
    'mistral_medium': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'mistral-medium-latest', 'fmt': 'openai', 'timeout': 15},
    'mistral_codestral': {'url': 'https://codestral.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'codestral-latest', 'fmt': 'openai', 'timeout': 15},
    'mistral_devstral': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'devstral-small-latest', 'fmt': 'openai', 'timeout': 20},
    'mistral_pixtral': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'pixtral-large-latest', 'fmt': 'openai', 'timeout': 20},
    'local': {'url': LM_URL, 'key': '', 'model': 'local-model', 'fmt': 'openai', 'auth': 'bearer'},
    'zhipu_flash': {'url': 'https://open.bigmodel.cn/api/paas/v4/chat/completions', 'key': os.environ.get('ZHIPU_API_KEY', ''), 'model': 'glm-4-flash', 'fmt': 'openai', 'timeout': 10},
    'zhipu_flash7': {'url': 'https://open.bigmodel.cn/api/paas/v4/chat/completions', 'key': os.environ.get('ZHIPU_API_KEY', ''), 'model': 'glm-4.7-flash', 'fmt': 'openai', 'timeout': 10},
    'silicon_qwen8b': {'url': 'https://api.siliconflow.cn/v1/chat/completions', 'key': os.environ.get('SILICONFLOW_API_KEY', ''), 'model': 'Qwen/Qwen3-8B', 'fmt': 'openai', 'timeout': 10},
    'silicon_glm9b': {'url': 'https://api.siliconflow.cn/v1/chat/completions', 'key': os.environ.get('SILICONFLOW_API_KEY', ''), 'model': 'THUDM/glm-4-9b-chat', 'fmt': 'openai', 'timeout': 10},
    'silicon_deepseek': {'url': 'https://api.siliconflow.cn/v1/chat/completions', 'key': os.environ.get('SILICONFLOW_API_KEY', ''), 'model': 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B', 'fmt': 'openai', 'timeout': 15},
    'baidu_ernie': {'url': 'https://qianfan.baidubce.com/v2/chat/completions', 'key': os.environ.get('BAIDU_API_KEY', ''), 'model': 'ernie-3.5-8k', 'fmt': 'openai', 'auth': 'bearer', 'timeout': 10},
    'baidu_speed': {'url': 'https://qianfan.baidubce.com/v2/chat/completions', 'key': os.environ.get('BAIDU_API_KEY', ''), 'model': 'ernie-speed-8k', 'fmt': 'openai', 'auth': 'bearer', 'timeout': 8},
    'volcengine_doubao': {'url': 'https://ark.cn-beijing.volces.com/api/v3/chat/completions', 'key': os.environ.get('VOLCENGINE_API_KEY', ''), 'model': 'doubao-1-5-pro-256k', 'fmt': 'openai', 'timeout': 15},
    'aliyun_qwen3': {'url': 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions', 'key': os.environ.get('ALIYUN_API_KEY', ''), 'model': 'qwen3-8b', 'fmt': 'openai', 'timeout': 10},
    'aliyun_coder': {'url': 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions', 'key': os.environ.get('ALIYUN_API_KEY', ''), 'model': 'qwen-3-coder-plus', 'fmt': 'openai', 'timeout': 15},
    'tencent_hunyuan': {'url': 'https://api.hunyuan.cloud.tencent.com/v1/chat/completions', 'key': os.environ.get('TENCENT_API_KEY', ''), 'model': 'hunyuan-lite', 'fmt': 'openai', 'timeout': 10},
    'chat_ubi': {'url': 'https://ch.at/v1/chat/completions', 'key': 'none', 'model': 'gpt-3', 'fmt': 'openai', 'timeout': 20},
    'llm7': {'url': 'https://api.llm7.io/v1/chat/completions', 'key': 'none', 'model': 'auto', 'fmt': 'openai', 'timeout': 20},
    'pollinations': {'url': 'https://text.pollinations.ai/openai', 'key': 'none', 'model': 'openai', 'fmt': 'openai', 'timeout': 30},
    'naga_llama70b': {'url': 'https://api.naga.ai/v1/chat/completions', 'key': os.environ.get('NAGA_API_KEY', ''), 'model': 'llama-3.3-70b', 'fmt': 'openai', 'timeout': 20},
    'naga_gpt41mini': {'url': 'https://api.naga.ai/v1/chat/completions', 'key': os.environ.get('NAGA_API_KEY', ''), 'model': 'gpt-4.1-mini', 'fmt': 'openai', 'timeout': 20},
    'naga_glm45': {'url': 'https://api.naga.ai/v1/chat/completions', 'key': os.environ.get('NAGA_API_KEY', ''), 'model': 'glm-4.5-air', 'fmt': 'openai', 'timeout': 20},
    'naga_llama4': {'url': 'https://api.naga.ai/v1/chat/completions', 'key': os.environ.get('NAGA_API_KEY', ''), 'model': 'llama-4-scout', 'fmt': 'openai', 'timeout': 20},
    'freetheai_ds': {'url': 'https://api.freetheai.xyz/v1/chat/completions', 'key': os.environ.get('FREETHEAI_API_KEY', ''), 'model': 'yng/gemini-3-1-pro', 'fmt': 'openai', 'timeout': 20},
    'freetheai_gpt41': {'url': 'https://api.freetheai.xyz/v1/chat/completions', 'key': os.environ.get('FREETHEAI_API_KEY', ''), 'model': 'bbl/gpt-4.1', 'fmt': 'openai', 'timeout': 20},
    'freetheai_swe': {'url': 'https://api.freetheai.xyz/v1/chat/completions', 'key': os.environ.get('FREETHEAI_API_KEY', ''), 'model': 'wsf/swe-1.6', 'fmt': 'openai', 'timeout': 20},
    'zuki_codestral': {'url': 'https://zukijourney.com/v1/chat/completions', 'key': os.environ.get('ZUKI_API_KEY', ''), 'model': 'codestral-latest', 'fmt': 'openai', 'timeout': 20},
    'zuki_mistral_small': {'url': 'https://zukijourney.com/v1/chat/completions', 'key': os.environ.get('ZUKI_API_KEY', ''), 'model': 'mistral-small-latest', 'fmt': 'openai', 'timeout': 20},
    'featherless': {'url': 'https://api.featherless.ai/v1/chat/completions', 'key': os.environ.get('FEATHERLESS_API_KEY', ''), 'model': 'Qwen/Qwen3-32B', 'fmt': 'openai', 'timeout': 20},
    'glhf': {'url': 'https://glhf.chat/api/openai/v1/chat/completions', 'key': os.environ.get('GLHF_API_KEY', ''), 'model': 'hf:Qwen/Qwen3-32B', 'fmt': 'openai', 'timeout': 20},
    'agentrouter': {'url': 'https://agentrouter.org/v1/chat/completions', 'key': os.environ.get('AGENTROUTER_API_KEY', ''), 'model': 'qwen/qwen3-32b', 'fmt': 'openai', 'timeout': 20},
    # ── 新增: OpenCode Zen (零Key零注册, Big Pickle Stealth 72% SWE-bench) ──
    'opencode_stealth': {'url': 'https://opencode.ai/zen/v1/chat/completions', 'key': 'none', 'model': 'big-pickle', 'fmt': 'openai', 'timeout': 45},
    'opencode_ds_flash': {'url': 'https://opencode.ai/zen/v1/chat/completions', 'key': 'none', 'model': 'deepseek-v4-flash-free', 'fmt': 'openai', 'timeout': 30},
    'opencode_qwen': {'url': 'https://opencode.ai/zen/v1/chat/completions', 'key': 'none', 'model': 'qwen3.6-plus-free', 'fmt': 'openai', 'timeout': 30},
    'opencode_nemotron': {'url': 'https://opencode.ai/zen/v1/chat/completions', 'key': 'none', 'model': 'nemotron-3-super-free', 'fmt': 'openai', 'timeout': 30},
    'opencode_minimax': {'url': 'https://opencode.ai/zen/v1/chat/completions', 'key': 'none', 'model': 'minimax-m2.5-free', 'fmt': 'openai', 'timeout': 30},
    # ── 新增: Fireworks AI (Llama 3.1 405B 独家, 最大开源模型) ──
    'fireworks_llama405b': {'url': 'https://api.fireworks.ai/inference/v1/chat/completions', 'key': os.environ.get('FIREWORKS_API_KEY', ''), 'model': 'accounts/fireworks/models/llama-v3p1-405b-instruct', 'fmt': 'openai', 'timeout': 45},
    # ── 新增: OVHcloud (欧洲直连, 零注册, 40+模型, 待服务器验证可达性) ──
    'ovh_llama70b': {'url': 'https://llama-3-3-70b-instruct.endpoints.ai.cloud.ovh.net/v1/chat/completions', 'key': 'none', 'model': 'Llama-3.3-70B-Instruct', 'fmt': 'openai', 'timeout': 30},
    'ovh_deepseek': {'url': 'https://deepseek-r1-distill-qwen-32b.endpoints.ai.cloud.ovh.net/v1/chat/completions', 'key': 'none', 'model': 'DeepSeek-R1-Distill-Qwen-32B', 'fmt': 'openai', 'timeout': 45},
    # ── Cohere (Command A 系列, 自研 Mamba+Transformer 架构) ──
    'cohere_command': {'url': 'https://api.cohere.com/compatibility/v1/chat/completions', 'key': os.environ.get('COHERE_API_KEY', ''), 'model': 'command-a-03-2025', 'fmt': 'openai', 'timeout': 30},
    'cohere_command_plus': {'url': 'https://api.cohere.com/compatibility/v1/chat/completions', 'key': os.environ.get('COHERE_API_KEY', ''), 'model': 'command-a-plus-05-2026', 'fmt': 'openai', 'timeout': 30},
    'cohere_reasoning': {'url': 'https://api.cohere.com/compatibility/v1/chat/completions', 'key': os.environ.get('COHERE_API_KEY', ''), 'model': 'command-a-reasoning-08-2025', 'fmt': 'openai', 'timeout': 45},
    'cohere_vision': {'url': 'https://api.cohere.com/compatibility/v1/chat/completions', 'key': os.environ.get('COHERE_API_KEY', ''), 'model': 'command-a-vision-07-2025', 'fmt': 'openai', 'timeout': 30},
    # ── 新增: SambaNova Cloud (芯片级加速推理) ──
    'sambanova_llama4': {'url': 'https://api.sambanova.ai/v1/chat/completions', 'key': os.environ.get('SAMBANOVA_API_KEY', ''), 'model': 'Meta-Llama-4-Maverick-17B-128E-Instruct', 'fmt': 'openai', 'timeout': 20},
    'sambanova_ds_v3': {'url': 'https://api.sambanova.ai/v1/chat/completions', 'key': os.environ.get('SAMBANOVA_API_KEY', ''), 'model': 'DeepSeek-V3.2', 'fmt': 'openai', 'timeout': 30},
    # ── 新增: DeepInfra (200并发, 高吞吐) ──
    'deepinfra_llama4': {'url': 'https://api.deepinfra.com/v1/openai/chat/completions', 'key': os.environ.get('DEEPINFRA_API_KEY', ''), 'model': 'meta-llama/Llama-4-Maverick-17B-128E-Instruct', 'fmt': 'openai', 'timeout': 20},
    'deepinfra_qwen235b': {'url': 'https://api.deepinfra.com/v1/openai/chat/completions', 'key': os.environ.get('DEEPINFRA_API_KEY', ''), 'model': 'Qwen/Qwen3-235B-A22B-Instruct', 'fmt': 'openai', 'timeout': 30},
    'deepseek_free': {'url': 'http://127.0.0.1:8000/v1/chat/completions', 'key': 'none', 'model': 'deepseek-chat', 'fmt': 'openai', 'timeout': 60},
    # ── 本地 Ollama (RTX 5060 Ti 16GB, Cloudflare Tunnel 暴露) ──
    'local_coder14b': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'qwen2.5-coder:14b', 'fmt': 'openai', 'timeout': 30, 'caps': ['tool_calls']},
    'local_reasoning': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'deepseek-r1:7b', 'fmt': 'openai', 'timeout': 45, 'caps': ['deep_reasoning']},
    'local_general': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'gemma3:12b', 'fmt': 'openai', 'timeout': 30},
    'local_fast': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'qwen2.5-coder:1.5b', 'fmt': 'openai', 'timeout': 10},
    'local_chat': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'qwen2.5:0.5b', 'fmt': 'openai', 'timeout': 5},
    # ── DuckDuckGo-AI (本地 duckai, 免费, 仅 3 个模型验证可用) ──
    'ddg_gpt4o_mini': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'gpt-4o-mini', 'fmt': 'openai', 'timeout': 30, 'no_system': True, 'caps': ['tool_calls']},
    'ddg_gpt5_mini': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'gpt-5-mini', 'fmt': 'openai', 'timeout': 30, 'no_system': True, 'caps': ['tool_calls']},
    'ddg_claude_haiku_45': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'claude-haiku-4-5', 'fmt': 'openai', 'timeout': 30, 'no_system': True},
    'ddg_llama4': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'meta-llama/Llama-4-Scout-17B-16E-Instruct', 'fmt': 'openai', 'timeout': 30, 'no_system': True},
    'ddg_mistral': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'mistral-small-2603', 'fmt': 'openai', 'timeout': 20, 'no_system': True},
    'ddg_tinfoil_gptoss_120b': {'url': f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions", 'key': 'none', 'model': 'tinfoil/gpt-oss-120b', 'fmt': 'openai', 'timeout': 45, 'no_system': True},
    # ── lza6 系列 CF Workers (逆向网页 AI, 免费) ──
    'tele_reason': {'url': 'https://tele.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'teleprompt-reason', 'fmt': 'openai', 'timeout': 30},
    'tele_standard': {'url': 'https://tele.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'teleprompt-standard', 'fmt': 'openai', 'timeout': 30},
    'tele_apps': {'url': 'https://tele.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'teleprompt-apps', 'fmt': 'openai', 'timeout': 30},
    'assist_brainstorm': {'url': 'https://assist.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'brainstorm-tool', 'fmt': 'openai', 'timeout': 30},
    'vision_joycaption': {'url': 'https://vision.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'joy-caption-beta', 'fmt': 'openai', 'timeout': 30, 'caps': ['vision']},
    # ── StockAI (CF Worker, 9 模型, 免费) ──
    'stock_gpt4o_mini': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'openai/gpt-4o-mini', 'fmt': 'openai', 'timeout': 30},
    'stock_gemini_flash': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'google/gemini-2.0-flash', 'fmt': 'openai', 'timeout': 30},
    'stock_deepseek': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'deepseek/deepseek-chat-v3.1', 'fmt': 'openai', 'timeout': 30},
    'stock_llama4': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'meta/llama-4-scout', 'fmt': 'openai', 'timeout': 30},
    'stock_kimi_k2': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'moonshotai/kimi-k2', 'fmt': 'openai', 'timeout': 30},
    'stock_glm46': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'z-ai/glm-4.6', 'fmt': 'openai', 'timeout': 30},
    'stock_qwen3_coder': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'qwen/qwen3-coder', 'fmt': 'openai', 'timeout': 30},
    'stock_news': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'stockai/news', 'fmt': 'openai', 'timeout': 30},
    'stock_mistral': {'url': 'https://stock.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'mistral/mistral-small', 'fmt': 'openai', 'timeout': 30},
    # ── TheOldLLM v2 (本地代理 + 自动 Token 刷新, 免费) ──
    'oldllm_gpt54': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5.4', 'fmt': 'openai', 'timeout': 45},
    'oldllm_gpt53': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5.3', 'fmt': 'openai', 'timeout': 45},
    'oldllm_gpt52': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5.2', 'fmt': 'openai', 'timeout': 45},
    'oldllm_gpt51': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5.1', 'fmt': 'openai', 'timeout': 45},
    'oldllm_gpt5': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5', 'fmt': 'openai', 'timeout': 45, 'caps': ['tool_calls']},
    'oldllm_gpt5_mini': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-5-mini', 'fmt': 'openai', 'timeout': 30, 'caps': ['tool_calls']},
    'oldllm_gpt41': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-4.1', 'fmt': 'openai', 'timeout': 45},
    'oldllm_gpt41_mini': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-4.1-mini', 'fmt': 'openai', 'timeout': 30},
    'oldllm_gpt41_nano': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-4.1-nano', 'fmt': 'openai', 'timeout': 20},
    'oldllm_gpt4': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'gpt-4', 'fmt': 'openai', 'timeout': 45},
    'oldllm_o1': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'o1', 'fmt': 'openai', 'timeout': 60},
    'oldllm_o4_mini': {'url': 'https://llm.zhuguang.ccwu.cc/v1/chat/completions', 'key': '1', 'model': 'o4-mini', 'fmt': 'openai', 'timeout': 45},
    # ── Cloudflare Workers AI (免费 10K neurons/天, 大模型推理) ──
    'cfai_llama70b': {'url': 'https://ai.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'llama-3.3-70b', 'fmt': 'openai', 'timeout': 30, 'caps': ['tool_calls']},
    'cfai_llama4': {'url': 'https://ai.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'llama-4-scout', 'fmt': 'openai', 'timeout': 30},
    'cfai_qwen_coder': {'url': 'https://ai.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'qwen2.5-coder-32b', 'fmt': 'openai', 'timeout': 30, 'caps': ['tool_calls', 'code']},
    'cfai_deepseek_r1': {'url': 'https://ai.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'deepseek-r1-32b', 'fmt': 'openai', 'timeout': 45},
    'cfai_mistral': {'url': 'https://ai.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'mistral-small-3.1', 'fmt': 'openai', 'timeout': 30},
    # ── 本地 Ollama 新增模型 ──
    'local_qwen3': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'qwen3:8b', 'fmt': 'openai', 'timeout': 30},
    'local_phi4': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'phi4:14b', 'fmt': 'openai', 'timeout': 45},
    'local_mistral': {'url': f"{os.environ.get('OLLAMA_TUNNEL_URL', 'http://localhost:11434')}/v1/chat/completions", 'key': 'none', 'model': 'mistral', 'fmt': 'openai', 'timeout': 30},
    # ── PollinationsAI (免费, 直连, 无需 g4f 中间层) ──
    'pollinations_openai': {'url': 'https://text.pollinations.ai/openai/chat/completions', 'key': 'none', 'model': 'openai', 'fmt': 'openai', 'timeout': 30},
    'pollinations_openai_large': {'url': 'https://text.pollinations.ai/openai/chat/completions', 'key': 'none', 'model': 'openai-large', 'fmt': 'openai', 'timeout': 45},
    'pollinations_deepseek': {'url': 'https://text.pollinations.ai/openai/chat/completions', 'key': 'none', 'model': 'deepseek', 'fmt': 'openai', 'timeout': 30},
    'pollinations_qwen_coder': {'url': 'https://text.pollinations.ai/openai/chat/completions', 'key': 'none', 'model': 'qwen-coder', 'fmt': 'openai', 'timeout': 30},
    # ── 国家超算互联网平台 (scnet.cn, 免费 5 模型, 无需 Key/登录) ──
    'scnet_qwen30b': {'url': 'https://scnet.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'qwen3-30b', 'fmt': 'openai', 'timeout': 30},
    'scnet_minimax': {'url': 'https://scnet.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'minimax-m2.5', 'fmt': 'openai', 'timeout': 30},
    'scnet_qwen235b': {'url': 'https://scnet.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'qwen3-235b', 'fmt': 'openai', 'timeout': 45},
    'scnet_ds_flash': {'url': 'https://scnet.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'deepseek-v4-flash', 'fmt': 'openai', 'timeout': 30},
    'scnet_ds_pro': {'url': 'https://scnet.zhuguang.ccwu.cc/v1/chat/completions', 'key': 'none', 'model': 'deepseek-v4-pro', 'fmt': 'openai', 'timeout': 90},
    # ── Kimi (moonshot.cn, 登录后免费, K2 模型) ──
    # ── Kimi (moonshot.cn, 本地代理, K2.6 模型, 3 种模式) ──
    'kimi': {'url': 'http://localhost:4504/v1/chat/completions', 'key': 'none', 'model': 'kimi', 'fmt': 'openai', 'timeout': 45, 'private_code_allowed': True, 'admission': 'code_medium_candidate'},
    'kimi_thinking': {'url': 'http://localhost:4504/v1/chat/completions', 'key': 'none', 'model': 'kimi-thinking', 'fmt': 'openai', 'timeout': 45, 'private_code_allowed': True, 'admission': 'code_medium_candidate'},
    'kimi_search': {'url': 'http://localhost:4504/v1/chat/completions', 'key': 'none', 'model': 'kimi-search', 'fmt': 'openai', 'timeout': 60, 'private_code_allowed': True, 'admission': 'code_medium_candidate'},
    # ── MiMo 小米 (本地代理 port 4507, 网页逆向) ──
    'mimo_web': {'url': 'http://localhost:4507/v1/chat/completions', 'key': 'none', 'model': 'mimo-web', 'fmt': 'openai', 'timeout': 60, 'force_stream_param': True, 'admission': 'sandbox_only', 'private_code_allowed': False},
    'mimo_web_think': {'url': 'http://localhost:4507/v1/chat/completions', 'key': 'none', 'model': 'mimo-web-think', 'fmt': 'openai', 'timeout': 120, 'force_stream_param': True, 'admission': 'sandbox_only', 'private_code_allowed': False},
    'mimo_web_flash': {'url': 'http://localhost:4507/v1/chat/completions', 'key': 'none', 'model': 'mimo-web-flash', 'fmt': 'openai', 'timeout': 30, 'force_stream_param': True, 'admission': 'sandbox_only', 'private_code_allowed': False},
    # ── MiMo TTS (官方API, 限时免费) ──
    'mimo_tts': {'url': 'https://api.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_TTS_KEY', ''), 'model': 'mimo-v2.5-tts', 'fmt': 'openai', 'timeout': 30},
    'mimo_tts_v2': {'url': 'https://api.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_TTS_KEY', ''), 'model': 'mimo-v2-tts', 'fmt': 'openai', 'timeout': 30},
    # MiMo STT (WeChat/Telegram voice; input_audio via chat/completions, not routing pool)
    'mimo_stt': {'url': 'https://api.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_TTS_KEY', ''), 'model': 'mimo-v2-omni', 'fmt': 'openai', 'timeout': 45},
    # ── SCNet 大上下文 (本地代理, 文件上传突破 5 万字符限制, 需登录) ──
    'scnet_large_ds_flash': {'url': 'http://localhost:4505/v1/chat/completions', 'key': 'none', 'model': 'deepseek-v4-flash', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True},
    'scnet_large_ds_pro': {'url': 'http://localhost:4505/v1/chat/completions', 'key': 'none', 'model': 'deepseek-v4-pro', 'fmt': 'openai', 'timeout': 90},
}
