#!/usr/bin/env python3
"""
GRBL Training Data Extractor
Reads source files from GRBL-related repos and generates Chinese explanations
using Claude API, saving training pairs to grbl_training_data.json.
"""

import os
import json
import time
import re
import urllib.request
from dotenv import load_dotenv
load_dotenv()

# ── Configuration ────────────────────────────────────────────────────────────

REPOS = {
    "Grbl_Esp32_src": {
        "root": "D:/GIT/Grbl_Esp32/Grbl_Esp32/src",
        "extensions": [".cpp", ".h"],
        "lang": "cpp",
    },
    "Grbl_Esp32_Motors": {
        "root": "D:/GIT/Grbl_Esp32/Grbl_Esp32/src/Motors",
        "extensions": [".cpp", ".h"],
        "lang": "cpp",
    },
    "Grbl_Esp32_Spindles": {
        "root": "D:/GIT/Grbl_Esp32/Grbl_Esp32/src/Spindles",
        "extensions": [".cpp", ".h"],
        "lang": "cpp",
    },
    "GRBL-Plotter_MachineControl": {
        "root": "D:/GIT/GRBL-Plotter/GRBL-Plotter/MachineControl",
        "extensions": [".cs"],
        "lang": "csharp",
    },
    "GRBL-Plotter_GCodeCreation": {
        "root": "D:/GIT/GRBL-Plotter/GRBL-Plotter/GCodeCreation",
        "extensions": [".cs"],
        "lang": "csharp",
    },
    "LaserGRBL_Core": {
        "root": "D:/GIT/LaserGRBL/LaserGRBL/Core",
        "extensions": [".cs"],
        "lang": "csharp",
    },
    "LaserGRBL_ComWrapper": {
        "root": "D:/GIT/LaserGRBL/LaserGRBL/ComWrapper",
        "extensions": [".cs"],
        "lang": "csharp",
    },
    "bCNC": {
        "root": "D:/GIT/bCNC/bCNC",
        "extensions": [".py"],
        "lang": "python",
    },
}

OUTPUT_FILE = "D:/GIT/grbl_training_data.json"
CHECKPOINT_FILE = "D:/GIT/grbl_training_checkpoint.json"
MODEL = "claude-sonnet-4-6"
API_URL = "https://right.codes/claude-aws/v1/messages"
MAX_LINES = 200
MIN_LINES = 10
CHECKPOINT_EVERY = 10
RATE_LIMIT_DELAY = 0.5  # seconds between requests (2 req/s)

# Auto-generated file patterns to skip
SKIP_PATTERNS = [
    r"\.Designer\.cs$",
    r"\.resx$",
    r"AssemblyInfo",
    r"\.g\.cs$",
    r"\.generated\.",
    r"obj[/\\]",
    r"bin[/\\]",
    r"__pycache__",
]

# ── Helpers ───────────────────────────────────────────────────────────────────

def is_autogenerated(path: str) -> bool:
    for pat in SKIP_PATTERNS:
        if re.search(pat, path, re.IGNORECASE):
            return True
    return False


def collect_files() -> list[dict]:
    """Walk repos and collect candidate files under MAX_LINES."""
    candidates = []
    for repo_name, cfg in REPOS.items():
        root = cfg["root"]
        if not os.path.isdir(root):
            print(f"  [WARN] Directory not found: {root}")
            continue
        for dirpath, _dirs, files in os.walk(root):
            for fname in files:
                fpath = os.path.join(dirpath, fname)
                if is_autogenerated(fpath):
                    continue
                ext = os.path.splitext(fname)[1].lower()
                if ext not in cfg["extensions"]:
                    continue
                try:
                    with open(fpath, "r", encoding="utf-8", errors="replace") as f:
                        lines = f.readlines()
                    line_count = len(lines)
                    if MIN_LINES <= line_count <= MAX_LINES:
                        candidates.append({
                            "repo": repo_name,
                            "path": fpath,
                            "lang": cfg["lang"],
                            "lines": line_count,
                            "code": "".join(lines),
                        })
                except Exception as e:
                    print(f"  [WARN] Could not read {fpath}: {e}")
    return candidates


def load_checkpoint() -> tuple[list, set]:
    """Load existing results and set of already-processed paths."""
    if os.path.exists(CHECKPOINT_FILE):
        with open(CHECKPOINT_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        results = data.get("results", [])
        done = set(data.get("done_paths", []))
        print(f"  Resumed from checkpoint: {len(results)} items already done.")
        return results, done
    return [], set()


def save_checkpoint(results: list, done: set) -> None:
    with open(CHECKPOINT_FILE, "w", encoding="utf-8") as f:
        json.dump({"results": results, "done_paths": list(done)}, f,
                  ensure_ascii=False, indent=2)


def save_final(results: list) -> None:
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\n  Saved {len(results)} training pairs to {OUTPUT_FILE}")


# ── Claude API ────────────────────────────────────────────────────────────────

def build_prompt(item: dict) -> str:
    lang_map = {"cpp": "C++", "csharp": "C#", "python": "Python"}
    lang_label = lang_map.get(item["lang"], item["lang"])
    fname = os.path.basename(item["path"])
    return (
        f"你是一位精通CNC/GRBL嵌入式系统的中文技术专家。\n"
        f"请用中文详细解释以下来自 {item['repo']} 项目的 {lang_label} 代码文件 `{fname}` 的功能。\n"
        f"要求：\n"
        f"1. 说明该文件/模块的主要职责\n"
        f"2. 解释关键函数或类的作用\n"
        f"3. 说明与GRBL运动控制系统的关系\n"
        f"4. 如有重要算法或数据结构，请简要说明\n"
        f"回答请控制在300字以内，使用清晰的中文技术语言。"
    )


def generate_explanation(api_key: str, item: dict) -> str:
    lang_map = {"cpp": "cpp", "csharp": "csharp", "python": "python"}
    lang = lang_map.get(item["lang"], item["lang"])
    user_content = (
        f"解释这段GRBL代码的功能:\n"
        f"```{lang}\n{item['code']}\n```"
    )
    payload = json.dumps({
        "model": MODEL,
        "max_tokens": 1024,
        "system": build_prompt(item),
        "messages": [{"role": "user", "content": user_content}],
    }).encode("utf-8")
    req = urllib.request.Request(
        API_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["content"][0]["text"].strip()


def make_training_pair(item: dict, explanation: str) -> dict:
    lang_map = {"cpp": "cpp", "csharp": "csharp", "python": "python"}
    lang = lang_map.get(item["lang"], item["lang"])
    return {
        "messages": [
            {
                "role": "user",
                "content": (
                    f"解释这段GRBL代码的功能:\n"
                    f"```{lang}\n{item['code']}\n```"
                ),
            },
            {
                "role": "assistant",
                "content": explanation,
            },
        ],
        "metadata": {
            "repo": item["repo"],
            "file": os.path.basename(item["path"]),
            "lines": item["lines"],
            "lang": item["lang"],
        },
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main(test_mode: bool = False):
    api_key = os.environ.get("CLAUDE_API_KEY") or os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError("CLAUDE_API_KEY or ANTHROPIC_API_KEY environment variable not set.")

    print("Collecting candidate files...")
    candidates = collect_files()
    print(f"  Found {len(candidates)} files under {MAX_LINES} lines.")

    if test_mode:
        candidates = candidates[:3]
        print(f"  TEST MODE: processing only {len(candidates)} files.")

    results, done_paths = load_checkpoint()
    pending = [c for c in candidates if c["path"] not in done_paths]
    print(f"  {len(pending)} files to process.")

    for i, item in enumerate(pending):
        fname = os.path.basename(item["path"])
        print(f"  [{i+1}/{len(pending)}] {item['repo']}/{fname} ({item['lines']} lines)...")
        try:
            explanation = generate_explanation(api_key, item)
            pair = make_training_pair(item, explanation)
            results.append(pair)
            done_paths.add(item["path"])

            if (len(results) % CHECKPOINT_EVERY) == 0:
                save_checkpoint(results, done_paths)
                print(f"    Checkpoint saved ({len(results)} items).")

            time.sleep(RATE_LIMIT_DELAY)

        except Exception as e:
            print(f"    [ERROR] {fname}: {e}")
            time.sleep(2)
            continue

    save_final(results)
    # Clean up checkpoint after successful completion
    if os.path.exists(CHECKPOINT_FILE) and not test_mode:
        os.remove(CHECKPOINT_FILE)
    print("Done.")


if __name__ == "__main__":
    import sys
    test = "--test" in sys.argv
    main(test_mode=test)
