#!/bin/bash
# Fast-tune live NewAPI on JDCloud (/opt/newapi) — SQLite + compose Redis.
# Does NOT migrate MySQL, does NOT start :3001 sidecar.
# Usage on server: bash apply_newapi_fast_tune.sh

set -euo pipefail

NEWAPI_DIR="${NEWAPI_DIR:-/opt/newapi}"
COMPOSE="${NEWAPI_DIR}/docker-compose.yml"
ENV_FILE="${NEWAPI_DIR}/.env"
STAMP=$(date +%Y%m%d_%H%M%S)

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[INFO]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

[ -d "$NEWAPI_DIR" ] || die "missing $NEWAPI_DIR"
[ -f "$COMPOSE" ] || die "missing $COMPOSE"

cd "$NEWAPI_DIR"
info "Backup compose + sqlite"
cp -a docker-compose.yml "docker-compose.yml.bak.${STAMP}"
[ -f data/one-api.db ] && cp -a data/one-api.db "data/one-api.db.bak.${STAMP}"

# Reuse existing secrets if present
CRYPTO_SECRET=""
SESSION_SECRET=""
if [ -f "$ENV_FILE" ]; then
  CRYPTO_SECRET=$(grep -E '^CRYPTO_SECRET=' "$ENV_FILE" | cut -d= -f2- || true)
  SESSION_SECRET=$(grep -E '^SESSION_SECRET=' "$ENV_FILE" | cut -d= -f2- || true)
fi
[ -n "$CRYPTO_SECRET" ] || CRYPTO_SECRET=$(openssl rand -hex 32)
[ -n "$SESSION_SECRET" ] || SESSION_SECRET=$(openssl rand -hex 24)

cat > "$ENV_FILE" <<EOF
# generated by apply_newapi_fast_tune.sh ${STAMP}
CRYPTO_SECRET=${CRYPTO_SECRET}
SESSION_SECRET=${SESSION_SECRET}
EOF
chmod 600 "$ENV_FILE"
info "Wrote $ENV_FILE (chmod 600)"

export NEWAPI_DIR
python3 <<'PY'
from pathlib import Path
import os
import re

base = Path(os.environ.get("NEWAPI_DIR", "/opt/newapi"))
path = base / "docker-compose.yml"
text = path.read_text(encoding="utf-8")

if "env_file:" not in text:
    text = text.replace(
        "    environment:\n",
        "    env_file:\n      - .env\n    environment:\n",
        1,
    )

wanted = {
    "CRYPTO_SECRET": "CRYPTO_SECRET=${CRYPTO_SECRET}",
    "SESSION_SECRET": "SESSION_SECRET=${SESSION_SECRET}",
    "STREAMING_TIMEOUT": "STREAMING_TIMEOUT=600",
    "STREAM_SCANNER_MAX_BUFFER_MB": "STREAM_SCANNER_MAX_BUFFER_MB=128",
    "REDIS_POOL_SIZE": "REDIS_POOL_SIZE=24",
    "MAX_REQUEST_BODY_MB": "MAX_REQUEST_BODY_MB=48",
    "MEMORY_CACHE_ENABLED": "MEMORY_CACHE_ENABLED=true",
}

# Ensure MEMORY_CACHE stays true; upsert keys under new-api environment
for key, line in wanted.items():
    pattern = rf"^(\s*-\s*){re.escape(key)}=.*$"
    if re.search(pattern, text, flags=re.M):
        text = re.sub(pattern, rf"\1{line}", text, flags=re.M)
    else:
        # insert after environment: block start (first env_file-aware environment)
        text = re.sub(
            r"(env_file:\n\s+-\s+\.env\n\s+environment:\n)",
            rf"\1      - {line}\n",
            text,
            count=1,
        )
        if f"- {line}" not in text and f"{key}=" not in text:
            text = text.replace(
                "    environment:\n",
                f"    environment:\n      - {line}\n",
                1,
            )

path.write_text(text, encoding="utf-8")
print("patched docker-compose.yml")
PY

info "Restart stack"
if command -v docker-compose >/dev/null 2>&1; then
  docker-compose up -d || {
    warn "docker-compose up failed (ContainerConfig?); force recreate"
    docker ps -aq --filter name=newapi_new-api --filter name=new-api | xargs -r docker rm -f
    docker-compose up -d
  }
else
  docker compose up -d
fi
sleep 5
info "Smoke status"
curl -sf http://127.0.0.1:3000/api/status | head -c 220 || warn "status probe failed"
echo
CID=$(docker ps -qf name=newapi_new-api | head -1)
if [ -n "$CID" ]; then
  docker exec "$CID" printenv CRYPTO_SECRET >/dev/null 2>&1 \
    && info "CRYPTO_SECRET visible in container" \
    || warn "CRYPTO_SECRET not visible yet — check env_file / service name"
else
  warn "new-api container not found"
fi

echo
echo "=========================================="
echo " Fast tune done. Next: Web UI + Kimi CLI"
echo "  1) Redis cache ON, retry>=2, close register"
echo "  2) Claude header: anthropic-beta: prompt-caching-2024-07-01"
echo "  3) Kimi CLI base_url=https://api.donglicao.com/v1"
echo " Doc: docs/ops/NEWAPI_KIMI_IMPROVEMENT_PLAN_CN.md"
echo "=========================================="
