#!/usr/bin/env bash
# Deploy the LiMa JDCloud proxy worker on the JDCloud node.
set -euo pipefail

[[ $EUID -ne 0 ]] && { echo "Run as root"; exit 1; }

WORK_DIR="/opt/lima-worker"
PROVIDERS_DIR="${WORK_DIR}/providers"
SERVICE_NAME="jdcloud-worker.service"
LOCAL_WORKER="deploy/jdcloud/jdcloud_worker.py"
LOCAL_SERVICE="deploy/jdcloud/jdcloud-worker.service"
LOCAL_REQUIREMENTS="deploy/jdcloud/jdcloud-worker-requirements.txt"

echo "==> Creating lima-worker user if missing"
if ! id -u lima-worker &>/dev/null; then
    useradd --system --user-group --home-dir "${WORK_DIR}" --create-home lima-worker
fi

echo "==> Creating directories"
mkdir -p "${WORK_DIR}" "${PROVIDERS_DIR}"
chown -R lima-worker:lima-worker "${WORK_DIR}"

echo "==> Creating Python virtual environment"
python3 -m venv "${WORK_DIR}/venv"
"${WORK_DIR}/venv/bin/pip" install --upgrade pip
"${WORK_DIR}/venv/bin/pip" install -r "${LOCAL_REQUIREMENTS}"

echo "==> Installing worker code"
if [[ ! -f "${LOCAL_WORKER}" ]]; then
    echo "ERROR: ${LOCAL_WORKER} not found. Run this script from the project root." >&2
    exit 1
fi
cp "${LOCAL_WORKER}" "${WORK_DIR}/jdcloud_worker.py"
chown lima-worker:lima-worker "${WORK_DIR}/jdcloud_worker.py"

echo "==> Creating environment file"
if [[ ! -f "${WORK_DIR}/.env" ]]; then
    cat > "${WORK_DIR}/.env" <<'EOF'
# LiMa JDCloud Proxy Worker environment
# Generated by deploy_jdcloud_worker.sh

# Required: shared secret used by LiMa Router
JDCLOUD_WORKER_TOKEN=change-me-in-production

# Bind address (Tailscale interface)
JDCLOUD_WORKER_HOST=100.85.114.65
JDCLOUD_WORKER_PORT=8700

# Provider configs: {PROVIDER}_URL and {PROVIDER}_KEY (case-insensitive)
# Keyless free providers omit {PROVIDER}_KEY entirely; the worker forwards
# without an Authorization header.

# Pollinations (keyless free upstream, OpenAI-compatible) — pilot
POLLINATIONS_URL=https://text.pollinations.ai/openai/chat/completions

# Example keyed provider (uncomment and fill in to use):
# FREE_OPENAI_NEXT_URL=https://...
# FREE_OPENAI_NEXT_KEY=sk-...
EOF
fi
chmod 600 "${WORK_DIR}/.env"
chown lima-worker:lima-worker "${WORK_DIR}/.env"

echo "==> Validating worker token"
JDCLOUD_WORKER_TOKEN=""
# shellcheck source=/dev/null
source "${WORK_DIR}/.env"
if [[ -z "${JDCLOUD_WORKER_TOKEN:-}" || "${JDCLOUD_WORKER_TOKEN}" == "change-me-in-production" ]]; then
    echo "ERROR: JDCLOUD_WORKER_TOKEN is unset, empty, or still set to the placeholder." >&2
    echo "Edit ${WORK_DIR}/.env and set a strong JDCLOUD_WORKER_TOKEN, then re-run this script." >&2
    exit 1
fi

echo "==> Installing systemd service"
if [[ ! -f "${LOCAL_SERVICE}" ]]; then
    echo "ERROR: ${LOCAL_SERVICE} not found. Run this script from the project root." >&2
    exit 1
fi
if [[ -f "/etc/systemd/system/${SERVICE_NAME}" ]]; then
    cp "/etc/systemd/system/${SERVICE_NAME}" "/etc/systemd/system/${SERVICE_NAME}.bak"
fi
cp "${LOCAL_SERVICE}" "/etc/systemd/system/${SERVICE_NAME}"
chmod 644 "/etc/systemd/system/${SERVICE_NAME}"

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"

chown -R lima-worker:lima-worker "${WORK_DIR}"

echo "==> Starting service"
if systemctl is-active --quiet "${SERVICE_NAME}"; then
    systemctl restart "${SERVICE_NAME}"
else
    systemctl start "${SERVICE_NAME}"
fi

echo "==> Waiting for service to become active"
sleep 2
for _ in {1..10}; do
    if systemctl is-active --quiet "${SERVICE_NAME}"; then
        break
    fi
    sleep 1
done

if ! systemctl is-active --quiet "${SERVICE_NAME}"; then
    echo "ERROR: Service ${SERVICE_NAME} is not active." >&2
    systemctl status --no-pager "${SERVICE_NAME}" >&2 || true
    exit 1
fi

echo "==> Service status"
systemctl status --no-pager "${SERVICE_NAME}"

echo "==> Deployment complete"
