#!/bin/bash
# Tune JDCloud new-api for Kimi Code CLI cache hit rate.
# - Enables Redis + MEMORY_CACHE relay dedup (new-api official)
# - Adds optional newapi-claude on :3001 for Claude Opus + prompt-cache headers
# - Tunes Redis memory policy for cache workloads
#
# Run ON SERVER (117.72.118.95):
#   bash deploy/jdcloud/tune_newapi_kimi_cache.sh
# Or from repo root via SSH:
#   scp deploy/jdcloud/tune_newapi_kimi_cache.sh root@117.72.118.95:/tmp/
#   ssh root@117.72.118.95 'bash /tmp/tune_newapi_kimi_cache.sh'

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

NEWAPI_DIR="/opt/newapi"
COMPOSE="${NEWAPI_DIR}/docker-compose.yml"
ENV_FILE="${NEWAPI_DIR}/.env.kimi-cache"
CLAUDE_COMPOSE_SRC="$(dirname "$0")/docker-compose.newapi-claude.yml"
ENV_EXAMPLE="$(dirname "$0")/docker-compose.newapi-kimi-cache.env.example"
STAMP=$(date +%Y%m%d_%H%M%S)

[ -d "$NEWAPI_DIR" ] || error "Missing ${NEWAPI_DIR}; run install_newapi.sh first"
[ -f "$COMPOSE" ] || error "Missing ${COMPOSE}"

info "Backup compose -> ${COMPOSE}.bak.${STAMP}"
cp -a "$COMPOSE" "${COMPOSE}.bak.${STAMP}"

# ── 1. Resolve Redis password from running container or prompt ─────────────
REDIS_PASS=""
if docker ps --format '{{.Names}}' | grep -qx newapi; then
  REDIS_CONN=$(docker inspect newapi --format '{{range .Config.Env}}{{println .}}{{end}}' | grep '^REDIS_CONN_STRING=' | cut -d= -f2- || true)
  if [[ "$REDIS_CONN" =~ redis://:([^@]+)@ ]]; then
    REDIS_PASS="${BASH_REMATCH[1]}"
  fi
fi
if [ -z "$REDIS_PASS" ] && [ -f /etc/redis/redis.conf ]; then
  REDIS_PASS=$(grep -E '^requirepass ' /etc/redis/redis.conf | awk '{print $2}' || true)
fi
if [ -z "$REDIS_PASS" ]; then
  read -r -s -p "Redis requirepass (hidden): " REDIS_PASS; echo
fi
[ -n "$REDIS_PASS" ] || error "Redis password required for cache tuning"

CRYPTO_SECRET=""
if [ -f "$ENV_FILE" ]; then
  CRYPTO_SECRET=$(grep -E '^CRYPTO_SECRET=' "$ENV_FILE" | cut -d= -f2- || true)
fi
[ -n "$CRYPTO_SECRET" ] || CRYPTO_SECRET=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# generated by tune_newapi_kimi_cache.sh ${STAMP}
REDIS_CONN_STRING=redis://:${REDIS_PASS}@127.0.0.1:6379/0
REDIS_CONN_STRING_CLAUDE=redis://:${REDIS_PASS}@127.0.0.1:6379/1
CRYPTO_SECRET=${CRYPTO_SECRET}
MEMORY_CACHE_ENABLED=true
REDIS_POOL_SIZE=24
SYNC_FREQUENCY=30
STREAMING_TIMEOUT=600
STREAM_SCANNER_MAX_BUFFER_MB=128
MAX_REQUEST_BODY_MB=48
BATCH_UPDATE_ENABLED=true
BATCH_UPDATE_INTERVAL=5
ERROR_LOG_ENABLED=true
EOF
chmod 600 "$ENV_FILE"
info "Wrote ${ENV_FILE}"

# ── 2. Patch main docker-compose environment ───────────────────────────────
python3 <<'PY'
from pathlib import Path
import re

compose = Path("/opt/newapi/docker-compose.yml")
text = compose.read_text(encoding="utf-8")
extra = [
    "MEMORY_CACHE_ENABLED=true",
    "CRYPTO_SECRET=${CRYPTO_SECRET}",
    "REDIS_POOL_SIZE=24",
    "SYNC_FREQUENCY=30",
    "STREAMING_TIMEOUT=600",
    "STREAM_SCANNER_MAX_BUFFER_MB=128",
    "MAX_REQUEST_BODY_MB=48",
    "BATCH_UPDATE_INTERVAL=5",
]
if "env_file:" not in text:
    text = text.replace(
        "    environment:\n",
        "    env_file:\n      - .env.kimi-cache\n    environment:\n",
        1,
    )
for line in extra:
    key = line.split("=", 1)[0]
    if re.search(rf"^\s*-\s*{re.escape(key)}=", text, re.M):
        text = re.sub(rf"^\s*-\s*{re.escape(key)}=.*$", f"      - {line}", text, flags=re.M)
    else:
        text = text.replace(
            "    environment:\n",
            f"    environment:\n      - {line}\n",
            1,
        )
compose.write_text(text, encoding="utf-8")
print("patched docker-compose.yml")
PY

# ── 3. Redis cache-friendly memory policy ──────────────────────────────────
if [ -f /etc/redis/redis.conf ]; then
  sed -i 's/^maxmemory-policy .*/maxmemory-policy allkeys-lru/' /etc/redis/redis.conf || true
  if ! grep -q '^maxmemory ' /etc/redis/redis.conf; then
    echo "maxmemory 1536mb" >> /etc/redis/redis.conf
  fi
  systemctl restart redis-server || warn "redis restart failed (check manually)"
  info "Redis maxmemory-policy -> allkeys-lru"
fi

# ── 4. Restart main new-api ────────────────────────────────────────────────
cd "$NEWAPI_DIR"
docker compose pull
docker compose up -d
info "Restarted newapi :3000"

# ── 5. Optional Claude sidecar (:3001) ─────────────────────────────────────
if [ -f "$CLAUDE_COMPOSE_SRC" ]; then
  cp -a "$CLAUDE_COMPOSE_SRC" "${NEWAPI_DIR}/docker-compose.claude.yml"
  mkdir -p "${NEWAPI_DIR}/data-claude" "${NEWAPI_DIR}/logs-claude"
  # Export DSN parts from main compose for claude sidecar
  SQL_DSN=$(docker inspect newapi --format '{{range .Config.Env}}{{println .}}{{end}}' | grep '^SQL_DSN=' | cut -d= -f2-)
  export NEWAPI_MYSQL_USER=$(echo "$SQL_DSN" | sed -E 's#^([^:]+):.*#\1#')
  export NEWAPI_MYSQL_PASS=$(echo "$SQL_DSN" | sed -E 's#^[^:]+:([^@]+)@.*#\1#')
  set -a; source "$ENV_FILE"; set +a
  docker compose -f docker-compose.claude.yml up -d
  info "Started newapi-claude :3001 (shared DB, Redis DB 1)"
else
  warn "docker-compose.newapi-claude.yml not found beside script; skip :3001 sidecar"
fi

# ── 6. Enable cache flag in DB options (best-effort) ─────────────────────
if command -v mysql >/dev/null 2>&1 && [ -n "${SQL_DSN:-}" ]; then
  MYSQL_USER="${NEWAPI_MYSQL_USER:-newapi}"
  MYSQL_PASS="${NEWAPI_MYSQL_PASS:-}"
  if [ -n "$MYSQL_PASS" ]; then
    mysql -u "$MYSQL_USER" -p"$MYSQL_PASS" -h 127.0.0.1 newapi -e "
      INSERT INTO options (\`key\`, value) VALUES ('CacheEnabled', 'true')
        ON DUPLICATE KEY UPDATE value='true';
      INSERT INTO options (\`key\`, value) VALUES ('CacheTTL', '3600')
        ON DUPLICATE KEY UPDATE value='3600';
    " 2>/dev/null && info "DB options CacheEnabled/CacheTTL set" || warn "Could not update options table (use Web UI)"
  fi
fi

# ── 7. Smoke ───────────────────────────────────────────────────────────────
curl -sf http://127.0.0.1:3000/api/status | head -c 200; echo
if curl -sf http://127.0.0.1:3001/api/status >/dev/null 2>&1; then
  curl -sf http://127.0.0.1:3001/api/status | head -c 200; echo
fi

echo ""
echo "=========================================="
echo " Kimi Code CLI cache tune complete"
echo "=========================================="
echo " Main:   http://127.0.0.1:3000  (public https://api.donglicao.com/v1)"
echo " Claude: http://127.0.0.1:3001/v1  (loopback / SSH tunnel for Kimi provider)"
echo ""
echo "Next (Web UI https://api.donglicao.com):"
echo "  1. 系统设置 → 运营设置 → 启用 Redis 缓存"
echo "  2. Claude 渠道 → 自定义 Header: anthropic-beta: prompt-caching-2024-07-01"
echo "  3. Kimi 渠道 → 模型 kimi-for-coding,kimi-for-coding-highspeed"
echo "Doc: docs/ops/NEWAPI_KIMI_CODE_CACHE_CN.md"
