"""Commercial backend definitions: cerebras family."""

import os

BACKENDS = {
    "cerebras_qwen235b": {
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "key": os.environ.get("CEREBRAS_API_KEY", ""),
        "model": "qwen-3-235b-a22b-instruct-2507",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "cerebras_llama8b": {
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "key": os.environ.get("CEREBRAS_API_KEY", ""),
        "model": "llama3.1-8b",
        "fmt": "openai",
        "timeout": 15,
    },
    "cerebras_gptoss": {
        "url": "https://api.cerebras.ai/v1/chat/completions",
        "key": os.environ.get("CEREBRAS_API_KEY", ""),
        "model": "gpt-oss-120b",
        "fmt": "openai",
        "timeout": 20,
    },
    "naga_llama70b": {
        "url": "https://api.naga.ai/v1/chat/completions",
        "key": os.environ.get("NAGA_API_KEY", ""),
        "model": "llama-3.3-70b",
        "fmt": "openai",
        "timeout": 20,
    },
    "naga_gpt41mini": {
        "url": "https://api.naga.ai/v1/chat/completions",
        "key": os.environ.get("NAGA_API_KEY", ""),
        "model": "gpt-4.1-mini",
        "fmt": "openai",
        "timeout": 20,
    },
    "naga_glm45": {
        "url": "https://api.naga.ai/v1/chat/completions",
        "key": os.environ.get("NAGA_API_KEY", ""),
        "model": "glm-4.5-air",
        "fmt": "openai",
        "timeout": 20,
    },
    "naga_llama4": {
        "url": "https://api.naga.ai/v1/chat/completions",
        "key": os.environ.get("NAGA_API_KEY", ""),
        "model": "llama-4-scout",
        "fmt": "openai",
        "timeout": 20,
    },
    "freetheai_ds": {
        "url": "https://api.freetheai.xyz/v1/chat/completions",
        "key": os.environ.get("FREETHEAI_API_KEY", ""),
        "model": "yng/gemini-3-1-pro",
        "fmt": "openai",
        "timeout": 20,
    },
    "freetheai_gpt41": {
        "url": "https://api.freetheai.xyz/v1/chat/completions",
        "key": os.environ.get("FREETHEAI_API_KEY", ""),
        "model": "bbl/gpt-4.1",
        "fmt": "openai",
        "timeout": 20,
    },
    "freetheai_swe": {
        "url": "https://api.freetheai.xyz/v1/chat/completions",
        "key": os.environ.get("FREETHEAI_API_KEY", ""),
        "model": "wsf/swe-1.6",
        "fmt": "openai",
        "timeout": 20,
    },
    "zuki_codestral": {
        "url": "https://zukijourney.com/v1/chat/completions",
        "key": os.environ.get("ZUKI_API_KEY", ""),
        "model": "codestral-latest",
        "fmt": "openai",
        "timeout": 20,
    },
    "zuki_mistral_small": {
        "url": "https://zukijourney.com/v1/chat/completions",
        "key": os.environ.get("ZUKI_API_KEY", ""),
        "model": "mistral-small-latest",
        "fmt": "openai",
        "timeout": 20,
    },
    "featherless": {
        "url": "https://api.featherless.ai/v1/chat/completions",
        "key": os.environ.get("FEATHERLESS_API_KEY", ""),
        "model": "Qwen/Qwen3-32B",
        "fmt": "openai",
        "timeout": 20,
    },
    "glhf": {
        "url": "https://glhf.chat/api/openai/v1/chat/completions",
        "key": os.environ.get("GLHF_API_KEY", ""),
        "model": "hf:Qwen/Qwen3-32B",
        "fmt": "openai",
        "timeout": 20,
    },
    "agentrouter": {
        "url": "https://agentrouter.org/v1/chat/completions",
        "key": os.environ.get("AGENTROUTER_API_KEY", ""),
        "model": "qwen/qwen3-32b",
        "fmt": "openai",
        "timeout": 20,
    },
}
