"""Commercial backend definitions: opengateway."""

import os

BACKENDS = {
    "ogw_gpt55": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5.5",
        "fmt": "openai",
        "timeout": 90,
        "caps": ["tool_calls"],
    },
    "ogw_gpt54": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5.4",
        "fmt": "openai",
        "timeout": 60,
        "caps": ["tool_calls"],
    },
    "ogw_gpt54_mini": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5.4-mini",
        "fmt": "openai",
        "timeout": 30,
    },
    "ogw_gpt5_codex": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5-codex",
        "fmt": "openai",
        "timeout": 60,
        "caps": ["tool_calls", "code"],
    },
    "ogw_gpt5_nano": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-5-nano",
        "fmt": "openai",
        "timeout": 15,
    },
    "ogw_gpt4o_mini": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "openai/gpt-4o-mini",
        "fmt": "openai",
        "timeout": 20,
        "caps": ["tool_calls"],
    },
    "ogw_claude_sonnet": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "anthropic/claude-sonnet-4-6",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls"],
    },
    "ogw_claude_haiku": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "anthropic/claude-haiku-4-5",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "ogw_deepseek_v4": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "deepseek/deepseek-v4-pro",
        "fmt": "openai",
        "timeout": 60,
        "caps": ["tool_calls"],
    },
    "ogw_deepseek_flash": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "deepseek/deepseek-v4-flash",
        "fmt": "openai",
        "timeout": 20,
        "caps": ["tool_calls"],
    },
    "ogw_grok": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "x-ai/grok-4.3",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls"],
    },
    "ogw_kimi": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "moonshotai/kimi-k2.6",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls"],
    },
    "ogw_glm5": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "z-ai/glm-5.1",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "ogw_gemini_flash": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "google/gemini-2.5-flash",
        "fmt": "openai",
        "timeout": 20,
    },
    "ogw_minimax": {
        "url": "https://api.opengateway.ai/v1/chat/completions",
        "key": os.environ.get("OPENGATEWAY_API_KEY", ""),
        "model": "minimax/MiniMax-M2.7",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
}
