"""Commercial backend definitions: platforms."""

from config.backend_config import (
    AGNES_AI_API_KEY,
    COHERE_API_KEY,
    DEEPINFRA_API_KEY,
    FIREWORKS_API_KEY,
    FREEMODEL_API_KEY,
    SAMBANOVA_API_KEY,
    TOGETHER_API_KEY,
    XMIAOM_API_KEY,
)

BACKENDS = {
    "fm_gpt55": {
        "url": "https://api.freemodel.dev/v1/chat/completions",
        "key": FREEMODEL_API_KEY,
        "model": "gpt-5.5",
        "fmt": "openai",
        "timeout": 90,
        "caps": ["tool_calls"],
    },
    "fm_gpt54": {
        "url": "https://api.freemodel.dev/v1/chat/completions",
        "key": FREEMODEL_API_KEY,
        "model": "gpt-5.4",
        "fmt": "openai",
        "timeout": 60,
        "caps": ["tool_calls"],
    },
    "fm_gpt54_mini": {
        "url": "https://api.freemodel.dev/v1/chat/completions",
        "key": FREEMODEL_API_KEY,
        "model": "gpt-5.4-mini",
        "fmt": "openai",
        "timeout": 30,
    },
    "fm_gpt53_codex": {
        "url": "https://api.freemodel.dev/v1/chat/completions",
        "key": FREEMODEL_API_KEY,
        "model": "gpt-5.3-codex",
        "fmt": "openai",
        "timeout": 60,
        "caps": ["tool_calls"],
    },
    "unclose_hermes": {
        "url": "https://hermes.ai.unturf.com/v1/chat/completions",
        "key": "none",
        "model": "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic",
        "fmt": "openai",
        "timeout": 15,
    },
    "unclose_qwen": {
        "url": "https://qwen.ai.unturf.com/v1/chat/completions",
        "key": "none",
        "model": "Qwen3.6-27B-UD-Q4_K_XL.gguf",
        "fmt": "openai",
        "timeout": 30,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    },
    "fireworks_llama405b": {
        "url": "https://api.fireworks.ai/inference/v1/chat/completions",
        "key": FIREWORKS_API_KEY,
        "model": "accounts/fireworks/models/llama-v3p1-405b-instruct",
        "fmt": "openai",
        "timeout": 45,
    },
    "ovh_llama70b": {
        "url": "https://llama-3-3-70b-instruct.endpoints.ai.cloud.ovh.net/v1/chat/completions",
        "key": "none",
        "model": "Llama-3.3-70B-Instruct",
        "fmt": "openai",
        "timeout": 30,
    },
    "ovh_deepseek": {
        "url": "https://deepseek-r1-distill-qwen-32b.endpoints.ai.cloud.ovh.net/v1/chat/completions",
        "key": "none",
        "model": "DeepSeek-R1-Distill-Qwen-32B",
        "fmt": "openai",
        "timeout": 45,
    },
    "cohere_command": {
        "url": "https://api.cohere.com/compatibility/v1/chat/completions",
        "key": COHERE_API_KEY,
        "model": "command-a-03-2025",
        "fmt": "openai",
        "timeout": 30,
    },
    "cohere_command_plus": {
        "url": "https://api.cohere.com/compatibility/v1/chat/completions",
        "key": COHERE_API_KEY,
        "model": "command-a-plus-05-2026",
        "fmt": "openai",
        "timeout": 30,
    },
    "cohere_reasoning": {
        "url": "https://api.cohere.com/compatibility/v1/chat/completions",
        "key": COHERE_API_KEY,
        "model": "command-a-reasoning-08-2025",
        "fmt": "openai",
        "timeout": 45,
    },
    "cohere_vision": {
        "url": "https://api.cohere.com/compatibility/v1/chat/completions",
        "key": COHERE_API_KEY,
        "model": "command-a-vision-07-2025",
        "fmt": "openai",
        "timeout": 30,
    },
    "sambanova_llama4": {
        "url": "https://api.sambanova.ai/v1/chat/completions",
        "key": SAMBANOVA_API_KEY,
        "model": "Meta-Llama-4-Maverick-17B-128E-Instruct",
        "fmt": "openai",
        "timeout": 20,
    },
    "sambanova_ds_v3": {
        "url": "https://api.sambanova.ai/v1/chat/completions",
        "key": SAMBANOVA_API_KEY,
        "model": "DeepSeek-V3.2",
        "fmt": "openai",
        "timeout": 30,
    },
    "sambanova_coder": {
        "url": "https://api.sambanova.ai/v1/chat/completions",
        "key": SAMBANOVA_API_KEY,
        "model": "DeepSeek-Coder-V2-Lite-Instruct",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "sambanova_qwen_coder": {
        "url": "https://api.sambanova.ai/v1/chat/completions",
        "key": SAMBANOVA_API_KEY,
        "model": "Qwen2.5-Coder-32B-Instruct",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "deepinfra_llama4": {
        "url": "https://api.deepinfra.com/v1/openai/chat/completions",
        "key": DEEPINFRA_API_KEY,
        "model": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
        "fmt": "openai",
        "timeout": 20,
    },
    "deepinfra_qwen235b": {
        "url": "https://api.deepinfra.com/v1/openai/chat/completions",
        "key": DEEPINFRA_API_KEY,
        "model": "Qwen/Qwen3-235B-A22B-Instruct",
        "fmt": "openai",
        "timeout": 30,
    },
    "deepinfra_coder": {
        "url": "https://api.deepinfra.com/v1/openai/chat/completions",
        "key": DEEPINFRA_API_KEY,
        "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "deepinfra_codellama": {
        "url": "https://api.deepinfra.com/v1/openai/chat/completions",
        "key": DEEPINFRA_API_KEY,
        "model": "codellama/CodeLlama-70b-Instruct-hf",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "together_qwen_coder": {
        "url": "https://api.together.xyz/v1/chat/completions",
        "key": TOGETHER_API_KEY,
        "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "together_codellama": {
        "url": "https://api.together.xyz/v1/chat/completions",
        "key": TOGETHER_API_KEY,
        "model": "codellama/CodeLlama-70b-Instruct-hf",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "together_deepseek_coder": {
        "url": "https://api.together.xyz/v1/chat/completions",
        "key": TOGETHER_API_KEY,
        "model": "deepseek-ai/deepseek-coder-33b-instruct",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "agnes20": {
        "url": "https://apihub.agnes-ai.com/v1/chat/completions",
        "key": AGNES_AI_API_KEY,
        "model": "agnes-2.0-flash",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls", "code"],
    },
    "agnes15": {
        "url": "https://apihub.agnes-ai.com/v1/chat/completions",
        "key": AGNES_AI_API_KEY,
        "model": "agnes-1.5-flash",
        "fmt": "openai",
        "timeout": 20,
        "caps": ["tool_calls"],
    },
    "xmiaom_gpt_image_2": {
        "url": "https://ai.xmiaom.com/v1/chat/completions",
        "key": XMIAOM_API_KEY,
        "model": "gpt-image-2",
        "fmt": "openai",
        "timeout": 120,
    },
}
