"""编程池后端定义（admission=code_* 的编程专用变体）"""
import os

BACKENDS = {
    # ── ModelScope 编程池 (code_medium_candidate) ──
    'ms_qwen35_27b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3.5-27B', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_kimi_k25_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'moonshotai/Kimi-K2.5', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_deepseek_v4_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'deepseek-ai/DeepSeek-V4-Flash', 'fmt': 'openai', 'timeout': 30, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_glm5_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'ZhipuAI/GLM-5', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_ds_v32_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'deepseek-ai/DeepSeek-V3.2', 'fmt': 'openai', 'timeout': 60, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_qwen3_235b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-235B-A22B', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_qwen3_coder_30b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-Coder-30B-A3B-Instruct', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_qwen3_next_80b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-Next-80B-A3B-Instruct', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_qwen35_122b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3.5-122B-A10B', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_glm51_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'ZhipuAI/GLM-5.1', 'fmt': 'openai', 'timeout': 60, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ms_step37_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'stepfun-ai/Step-3.7-Flash', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},

    # ── ModelScope 编程池 floor (code_floor_candidate, 非 tool_calls 但 code 能力强) ──
    'ms_ds_r1_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'deepseek-ai/DeepSeek-R1-0528', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen3_235b_think_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-235B-A22B-Thinking-2507', 'fmt': 'openai', 'timeout': 120, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen3_32b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-32B', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen3_next_80b_think_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3-Next-80B-A3B-Thinking', 'fmt': 'openai', 'timeout': 120, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen35_35b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3.5-35B-A3B', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen35_397b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen3.5-397B-A17B', 'fmt': 'openai', 'timeout': 120, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_mistral_large_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'mistralai/Mistral-Large-Instruct-2407', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_llama4_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'LLM-Research/Llama-4-Maverick-17B-128E-Instruct', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_interns2_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Shanghai_AI_Laboratory/Intern-S2-Preview', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen_coder_32b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen2.5-Coder-32B-Instruct', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen_coder_14b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen2.5-Coder-14B-Instruct', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},
    'ms_qwen_coder_7b_code': {'url': 'https://api-inference.modelscope.cn/v1/chat/completions', 'key': os.environ.get('MODELSCOPE_API_KEY', ''), 'model': 'Qwen/Qwen2.5-Coder-7B-Instruct', 'fmt': 'openai', 'timeout': 20, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['code']},

    # ── 其他平台编程池 ──
    'google_flash_code': {'url': 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions', 'key': os.environ.get('GOOGLE_AI_KEY', ''), 'model': 'gemini-2.5-flash', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'aliyun_qwen3_code': {'url': 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions', 'key': os.environ.get('ALIYUN_API_KEY', ''), 'model': 'qwen3-8b', 'fmt': 'openai', 'timeout': 20, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True},
    'xfyun_astron': {'url': 'https://maas-coding-api.cn-huabei-1.xf-yun.com/v2/chat/completions', 'key': os.environ.get('XFYUN_API_KEY', ''), 'model': 'astron-code-latest', 'fmt': 'openai', 'timeout': 30, 'auth': 'bearer', 'caps': ['tool_calls'], 'admission': 'code_medium_candidate', 'private_code_allowed': True},
    'dashscope_coding': {'url': 'https://coding.dashscope.aliyuncs.com/v1/chat/completions', 'key': os.environ.get('DASHSCOPE_CODING_KEY', ''), 'model': 'qwen3-coder-plus', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'zhihu_zhida': {'url': 'https://developer.zhihu.com/v1/chat/completions', 'key': os.environ.get('ZHIHU_API_KEY', ''), 'model': 'zhida-fast-1p5', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls'], 'extra_headers': {'X-Request-Timestamp': 'dynamic'}},
    'zhihu_zhida_think': {'url': 'https://developer.zhihu.com/v1/chat/completions', 'key': os.environ.get('ZHIHU_API_KEY', ''), 'model': 'zhida-thinking-1p5', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'extra_headers': {'X-Request-Timestamp': 'dynamic'}},
    'scnet_qwen235b_code': {'url': f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4505/v1/chat/completions", 'key': 'none', 'model': 'qwen3-235b', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'scnet_ds_pro_code': {'url': f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4505/v1/chat/completions", 'key': 'none', 'model': 'deepseek-v4-pro', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'or_gptoss_120b_code': {'url': 'https://openrouter.ai/api/v1/chat/completions', 'key': os.environ.get('OPENROUTER_API_KEY', ''), 'model': 'openai/gpt-oss-120b:free', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'cfai_qwen_coder_code': {'url': f"https://api.cloudflare.com/client/v4/accounts/{os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')}/ai/v1/chat/completions", 'key': os.environ.get('CLOUDFLARE_TOKEN', ''), 'model': '@cf/qwen/qwen2.5-coder-32b-instruct', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mistral_large_code': {'url': 'https://api.mistral.ai/v1/chat/completions', 'key': os.environ.get('MISTRAL_API_KEY', ''), 'model': 'mistral-large-latest', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'github_gpt4o_code': {'url': 'https://models.inference.ai.azure.com/chat/completions', 'key': os.environ.get('GITHUB_TOKEN', ''), 'model': 'gpt-4o', 'fmt': 'openai', 'timeout': 30, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_web_code': {'url': f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4507/v1/chat/completions", 'key': 'none', 'model': 'mimo-web', 'fmt': 'openai', 'timeout': 60, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_web_think_code': {'url': f"http://{os.environ.get('VPS_HOST', '47.112.162.80')}:4507/v1/chat/completions", 'key': 'none', 'model': 'mimo-web-think', 'fmt': 'openai', 'timeout': 120, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_v2_5_pro_code': {'url': 'https://token-plan-cn.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_V2_PRO_KEY', ''), 'model': 'mimo-v2.5-pro', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_v2_pro_code': {'url': 'https://token-plan-cn.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_V2_PRO_KEY', ''), 'model': 'mimo-v2-pro', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_v2_5_code': {'url': 'https://token-plan-cn.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_V2_PRO_KEY', ''), 'model': 'mimo-v2.5', 'fmt': 'openai', 'timeout': 45, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'mimo_v2_omni_code': {'url': 'https://token-plan-cn.xiaomimimo.com/v1/chat/completions', 'key': os.environ.get('MIMO_V2_PRO_KEY', ''), 'model': 'mimo-v2-omni', 'fmt': 'openai', 'timeout': 30, 'force_stream_param': True, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ogw_gpt5_codex_code': {'url': 'https://api.opengateway.ai/v1/chat/completions', 'key': os.environ.get('OPENGATEWAY_API_KEY', ''), 'model': 'openai/gpt-5-codex', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ogw_claude_sonnet_code': {'url': 'https://api.opengateway.ai/v1/chat/completions', 'key': os.environ.get('OPENGATEWAY_API_KEY', ''), 'model': 'anthropic/claude-sonnet-4-6', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ogw_deepseek_v4_code': {'url': 'https://api.opengateway.ai/v1/chat/completions', 'key': os.environ.get('OPENGATEWAY_API_KEY', ''), 'model': 'deepseek/deepseek-v4-pro', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},
    'ogw_gpt5_nano_code': {'url': 'https://api.opengateway.ai/v1/chat/completions', 'key': os.environ.get('OPENGATEWAY_API_KEY', ''), 'model': 'openai/gpt-5-nano', 'fmt': 'openai', 'timeout': 15, 'admission': 'code_floor_candidate', 'private_code_allowed': True},
    'agnes20_code': {'url': 'https://apihub.agnes-ai.com/v1/chat/completions', 'key': os.environ.get('AGNES_AI_API_KEY', ''), 'model': 'agnes-2.0-flash', 'fmt': 'openai', 'timeout': 45, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls', 'code']},
    'agnes15_code': {'url': 'https://apihub.agnes-ai.com/v1/chat/completions', 'key': os.environ.get('AGNES_AI_API_KEY', ''), 'model': 'agnes-1.5-flash', 'fmt': 'openai', 'timeout': 20, 'admission': 'code_floor_candidate', 'private_code_allowed': True, 'caps': ['tool_calls']},

    # ── 社区免费 API 编程池 ──
    'free_muyuan_gpt54_code': {'url': 'https://muyuan.do/v1/chat/completions', 'key': os.environ.get('FREE_MUYUAN_KEY', ''), 'model': 'gpt-5.4', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls'], 'headers': {'User-Agent': 'Mozilla/5.0'}},
    'free_muyuan_gpt55_code': {'url': 'https://muyuan.do/v1/chat/completions', 'key': os.environ.get('FREE_MUYUAN_KEY', ''), 'model': 'gpt-5.5', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls'], 'headers': {'User-Agent': 'Mozilla/5.0'}},
    'free_muyuan_codex_code': {'url': 'https://muyuan.do/v1/chat/completions', 'key': os.environ.get('FREE_MUYUAN_KEY', ''), 'model': 'codex-auto-review', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls', 'code'], 'headers': {'User-Agent': 'Mozilla/5.0'}},
    'free_ajiakesi_gpt54_code': {'url': 'http://codehub.ajiakesi.cn/v1/chat/completions', 'key': os.environ.get('FREE_AJIAKESI_KEY', ''), 'model': 'gpt-5.4', 'fmt': 'openai', 'timeout': 60, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls'], 'headers': {'User-Agent': 'Mozilla/5.0'}},
    'free_ajiakesi_gpt55_code': {'url': 'http://codehub.ajiakesi.cn/v1/chat/completions', 'key': os.environ.get('FREE_AJIAKESI_KEY', ''), 'model': 'gpt-5.5', 'fmt': 'openai', 'timeout': 90, 'admission': 'code_medium_candidate', 'private_code_allowed': True, 'caps': ['tool_calls'], 'headers': {'User-Agent': 'Mozilla/5.0'}},
}
