"""免费网页 AI 后端定义（lza6 系列、Pollinations、SCNet 等）"""

import os

BACKENDS = {
    # DuckAI local reverse proxy fallback models.
    "ddg_gpt4o_mini": {
        "url": f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions",
        "key": "none",
        "model": "gpt-4o-mini",
        "fmt": "openai",
        "timeout": 30,
        "no_system": True,
        "caps": ["tool_calls"],
    },
    "ddg_gpt5_mini": {
        "url": f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions",
        "key": "none",
        "model": "gpt-5-mini",
        "fmt": "openai",
        "timeout": 30,
        "no_system": True,
        "caps": ["tool_calls"],
    },
    "ddg_claude_haiku_45": {
        "url": f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions",
        "key": "none",
        "model": "claude-haiku-4-5",
        "fmt": "openai",
        "timeout": 30,
        "no_system": True,
    },
    "ddg_tinfoil_gptoss_120b": {
        "url": f"{os.environ.get('DDG_TUNNEL_URL', 'http://localhost:4500')}/v1/chat/completions",
        "key": "none",
        "model": "tinfoil/gpt-oss-120b",
        "fmt": "openai",
        "timeout": 45,
        "no_system": True,
    },
    # ── lza6 系列 CF Workers (逆向网页 AI, 免费) ──
    "tele_reason": {
        "url": "https://tele.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "teleprompt-reason",
        "fmt": "openai",
        "timeout": 30,
    },
    "tele_standard": {
        "url": "https://tele.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "teleprompt-standard",
        "fmt": "openai",
        "timeout": 30,
    },
    "tele_apps": {
        "url": "https://tele.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "teleprompt-apps",
        "fmt": "openai",
        "timeout": 30,
    },
    "assist_brainstorm": {
        "url": "https://assist.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "brainstorm-tool",
        "fmt": "openai",
        "timeout": 30,
    },
    "vision_joycaption": {
        "url": "https://vision.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "joy-caption-beta",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["vision"],
    },
    # ── StockAI (CF Worker, 9 模型, 免费) ──
    "stock_gpt4o_mini": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "openai/gpt-4o-mini",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_gemini_flash": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "google/gemini-2.0-flash",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_deepseek": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "deepseek/deepseek-chat-v3.1",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_llama4": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "meta/llama-4-scout",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_kimi_k2": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "moonshotai/kimi-k2",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_glm46": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "z-ai/glm-4.6",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_qwen3_coder": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "qwen/qwen3-coder",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_news": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "stockai/news",
        "fmt": "openai",
        "timeout": 30,
    },
    "stock_mistral": {
        "url": "https://stock.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "mistral/mistral-small",
        "fmt": "openai",
        "timeout": 30,
    },
    # ── TheOldLLM v2 (CF Worker, 自动 Token 刷新) ──
    "oldllm_gpt54": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5.4",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_gpt53": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5.3",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_gpt52": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5.2",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_gpt51": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5.1",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_gpt5": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls"],
    },
    "oldllm_gpt5_mini": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-5-mini",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "oldllm_gpt41": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-4.1",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_gpt41_mini": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-4.1-mini",
        "fmt": "openai",
        "timeout": 30,
    },
    "oldllm_gpt41_nano": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-4.1-nano",
        "fmt": "openai",
        "timeout": 20,
    },
    "oldllm_gpt4": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "gpt-4",
        "fmt": "openai",
        "timeout": 45,
    },
    "oldllm_o1": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "o1",
        "fmt": "openai",
        "timeout": 60,
    },
    "oldllm_o4_mini": {
        "url": "https://llm.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "1",
        "model": "o4-mini",
        "fmt": "openai",
        "timeout": 45,
    },
    # ── PollinationsAI (免费, 直连) ──
    "pollinations": {
        "url": "https://text.pollinations.ai/openai",
        "key": "none",
        "model": "openai",
        "fmt": "openai",
        "timeout": 30,
    },
    "pollinations_openai": {
        "url": "https://text.pollinations.ai/openai/chat/completions",
        "key": "none",
        "model": "openai",
        "fmt": "openai",
        "timeout": 30,
    },
    "pollinations_openai_large": {
        "url": "https://text.pollinations.ai/openai/chat/completions",
        "key": "none",
        "model": "openai-large",
        "fmt": "openai",
        "timeout": 45,
    },
    "pollinations_deepseek": {
        "url": "https://text.pollinations.ai/openai/chat/completions",
        "key": "none",
        "model": "deepseek",
        "fmt": "openai",
        "timeout": 30,
    },
    "pollinations_qwen_coder": {
        "url": "https://text.pollinations.ai/openai/chat/completions",
        "key": "none",
        "model": "qwen-coder",
        "fmt": "openai",
        "timeout": 30,
    },
    # ── 国家超算互联网平台 (scnet.cn CF Worker 代理, 5 模型) ──
    "scnet_qwen30b": {
        "url": "https://scnet.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "none",
        "model": "qwen3-30b",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "scnet_minimax": {
        "url": "https://scnet.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "none",
        "model": "minimax-m2.5",
        "fmt": "openai",
        "timeout": 30,
    },
    "scnet_qwen235b": {
        "url": "https://scnet.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "none",
        "model": "qwen3-235b",
        "fmt": "openai",
        "timeout": 45,
        "caps": ["tool_calls"],
    },
    "scnet_ds_flash": {
        "url": "https://scnet.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "none",
        "model": "deepseek-v4-flash",
        "fmt": "openai",
        "timeout": 30,
        "caps": ["tool_calls"],
    },
    "scnet_ds_pro": {
        "url": "https://scnet.zhuguang.ccwu.cc/v1/chat/completions",
        "key": "none",
        "model": "deepseek-v4-pro",
        "fmt": "openai",
        "timeout": 90,
        "caps": ["tool_calls"],
    },
    # ── 其他免费 ──
    "chat_ubi": {
        "url": "https://ch.at/v1/chat/completions",
        "key": "none",
        "model": "gpt-3",
        "fmt": "openai",
        "timeout": 20,
    },
    "llm7": {
        "url": "https://api.llm7.io/v1/chat/completions",
        "key": "none",
        "model": "auto",
        "fmt": "openai",
        "timeout": 20,
    },
}
