"""Compare provider inventories against LiMa backend registry."""

from __future__ import annotations

from typing import Any


def registered_backends(prefixes: tuple[str, ...]) -> dict[str, dict[str, str]]:
    from backends_registry import BACKENDS

    out: dict[str, dict[str, str]] = {}
    for name, cfg in BACKENDS.items():
        if not any(name.startswith(prefix) for prefix in prefixes):
            continue
        model = str(cfg.get("model") or "")
        out[name] = {"backend_key": name, "model_id": model, "url": str(cfg.get("url") or "")}
    return out


def registered_model_ids(prefixes: tuple[str, ...]) -> set[str]:
    return {entry["model_id"] for entry in registered_backends(prefixes).values() if entry["model_id"]}


def compare_inventory(
    inventory: dict[str, Any],
    *,
    backend_prefixes: tuple[str, ...],
) -> dict[str, Any]:
    remote_ids = {
        str(item.get("model_id") or "")
        for item in inventory.get("models", [])
        if isinstance(item, dict) and item.get("model_id")
    }
    registered = registered_backends(backend_prefixes)
    registered_ids = {entry["model_id"] for entry in registered.values() if entry["model_id"]}

    unregistered_remote = sorted(remote_ids - registered_ids)
    registered_not_in_remote = sorted(registered_ids - remote_ids)

    backend_by_model = {entry["model_id"]: entry["backend_key"] for entry in registered.values()}
    registered_in_remote = sorted(
        mid for mid in registered_ids if mid in remote_ids
    )

    return {
        "provider": inventory.get("provider"),
        "remote_count": len(remote_ids),
        "registered_backend_count": len(registered),
        "registered_in_remote": [
            {"model_id": mid, "backend_key": backend_by_model.get(mid, "")}
            for mid in registered_in_remote
        ],
        "unregistered_remote": unregistered_remote,
        "registered_missing_from_remote": [
            {"model_id": mid, "backend_key": backend_by_model.get(mid, "")}
            for mid in registered_not_in_remote
        ],
    }


def format_inventory_report(
    cf_inventory: dict[str, Any] | None,
    cf_diff: dict[str, Any] | None,
    google_inventory: dict[str, Any] | None,
    google_diff: dict[str, Any] | None,
) -> str:
    lines = ["# CF / Google Model Inventory Report", ""]
    lines.append("Generated by CF-G-0 inventory scripts.")
    lines.append("")

    if cf_inventory and cf_diff:
        lines.extend(_section("Cloudflare Workers AI", cf_inventory, cf_diff))
    else:
        lines.append("## Cloudflare Workers AI")
        lines.append("")
        lines.append("- Skipped (missing credentials or fetch failed)")
        lines.append("")

    if google_inventory and google_diff:
        lines.extend(_section("Google Generative Language API", google_inventory, google_diff))
    else:
        lines.append("## Google Generative Language API")
        lines.append("")
        lines.append("- Skipped (missing credentials or fetch failed)")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _section(title: str, inventory: dict[str, Any], diff: dict[str, Any]) -> list[str]:
    lines = [f"## {title}", ""]
    lines.append(f"- Remote models: **{diff.get('remote_count', 0)}**")
    lines.append(f"- Registered backends: **{diff.get('registered_backend_count', 0)}**")
    lines.append(f"- Registered and still listed remotely: **{len(diff.get('registered_in_remote', []))}**")
    lines.append(f"- Remote but not registered: **{len(diff.get('unregistered_remote', []))}**")
    lines.append("")

    unregistered = diff.get("unregistered_remote") or []
    if unregistered:
        lines.append("### Unregistered remote models")
        lines.append("")
        for model_id in unregistered[:40]:
            lines.append(f"- `{model_id}`")
        if len(unregistered) > 40:
            lines.append(f"- ... and {len(unregistered) - 40} more")
        lines.append("")

    missing = diff.get("registered_missing_from_remote") or []
    if missing:
        lines.append("### Registered locally but absent from remote list")
        lines.append("")
        for item in missing[:20]:
            lines.append(f"- `{item.get('backend_key')}` → `{item.get('model_id')}`")
        lines.append("")

    return lines
