use_default_settings: true

server:
  secret_key: "change-me-in-production"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"

ui:
  static_use_hash: true
