"""Seed data for known LiMa research references.

Each entry is a project, paper, or tool referenced in LiMa's architecture
docs. This file is the structured replacement for scattered doc references.
"""

from research_radar.source import (
    AdoptionState,
    LicenseClass,
    SourceRecord,
)

SEED_SOURCES: list[SourceRecord] = [
    SourceRecord(
        source_id="ref-lightrag",
        name="LightRAG",
        url="https://github.com/HKUDS/LightRAG",
        description="Graph-enhanced RAG with dual-layer retrieval (vector + graph).",
        tags=["rag", "graph", "retrieval", "knowledge"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="context_pipeline",
        notes="Inspired graph_retrieval.py CodeGraph and dual_layer_search. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-rerankers",
        name="Rerankers (AnswerDotAI)",
        url="https://github.com/AnswerDotAI/rerankers",
        description="Lightweight Python library for unified reranking API.",
        tags=["rag", "reranking", "search"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="context_pipeline",
        notes="Inspired reranking.py scoring factors. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-treesitter",
        name="tree-sitter",
        url="https://tree-sitter.github.io/",
        description="Incremental parsing library for multi-language AST extraction.",
        tags=["ast", "parsing", "code-analysis"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="code_context",
        notes="ast_adapter.py defines a tree-sitter boundary. Runtime adoption gated behind multi-language need.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-mem0",
        name="Mem0",
        url="https://github.com/mem0ai/mem0",
        description="Memory layer for AI agents with automatic memory extraction.",
        tags=["memory", "agent", "personalization"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="session_memory",
        notes="Inspired memory taxonomy and promotion rules in store.py. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-letta",
        name="Letta (MemGPT)",
        url="https://github.com/letta-ai/letta",
        description="Virtual context management with hierarchical memory.",
        tags=["memory", "context", "agent"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="session_memory",
        notes="Inspired hierarchical_memory.py layer design. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-promptfoo",
        name="Promptfoo",
        url="https://github.com/promptfoo/promptfoo",
        description="LLM evaluation framework with YAML-based test cases.",
        tags=["eval", "testing", "prompt-engineering"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="coding_eval",
        notes="Inspired coding_eval.py fixture format and grading logic. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-opentelemetry",
        name="OpenTelemetry Python",
        url="https://github.com/open-telemetry/opentelemetry-python",
        description="Observability framework for distributed tracing and metrics.",
        tags=["observability", "metrics", "tracing"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="observability",
        notes="observability/events.py and metrics.py are LiMa-native. OTEL exporter optional future.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-openai-agents",
        name="OpenAI Agents SDK",
        url="https://github.com/openai/openai-agents-python",
        description="Agent orchestration framework with tool use and handoffs.",
        tags=["agent", "tool-use", "orchestration"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="tool_gateway",
        notes="Inspired tool_gateway authority model and executor design. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-e2b",
        name="E2B Sandbox",
        url="https://github.com/e2b-dev/e2b",
        description="Cloud sandbox for AI code execution.",
        tags=["sandbox", "code-execution", "security"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="sandbox",
        notes="sandbox/provider.py defines E2B boundary. FakeSandboxProvider is the default.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-aider",
        name="Aider",
        url="https://github.com/paul-gauthier/aider",
        description="AI pair programming with SEARCH/REPLACE edit blocks.",
        tags=["code-editing", "prompt-engineering", "cli"],
        license_class=LicenseClass.APACHE2,
        adoption_state=AdoptionState.ADOPTED,
        subsystem="cli",
        notes="edit_protocol.py uses SEARCH/REPLACE block format. No runtime dependency.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-ruview",
        name="RuView",
        url="https://github.com/ruvnet/RuView",
        description="ESP32 WiFi CSI ambient perception reference.",
        tags=["hardware", "esp32", "wifi-sensing"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="device_gateway",
        notes="Hardware companion reference only. People-sensing default-off.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-shadowbroker",
        name="Shadowbroker AI Resources",
        url="https://github.com/BigBodyCobain/Shadowbroker",
        description="AI OSINT/resource reference reviewed as static-only input.",
        tags=["free-api", "provider", "catalog", "security"],
        license_class=LicenseClass.AGPL,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="provider_automation",
        notes="Static-only reference. Do not copy code or enable OSINT connectors by default.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-last30days",
        name="last30days AI Tools",
        url="https://github.com/mvanhorn/last30days-skill",
        description="Monthly curated list of new AI developer tools.",
        tags=["tools", "trending", "discovery"],
        license_class=LicenseClass.UNKNOWN,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="research_radar",
        notes="Discovery source for new tools. Individual evaluation required.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-leann",
        name="LEANN",
        url="https://github.com/yichuan-w/LEANN",
        description="Low-storage local vector index with recomputation and pruning.",
        tags=["retrieval", "vector-search", "ann", "local-index"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.CONCEPT_ONLY,
        subsystem="context_pipeline",
        notes="Potential future retrieval backend. Heavy dependency, not in runtime.",
        added_at="2026-05-24",
    ),
    SourceRecord(
        source_id="ref-gstack",
        name="GStack",
        url="https://github.com/gstack/gstack",
        description="Agent workflow with stage-gated plan/review/QA/ship pipeline.",
        tags=["workflow", "agent", "review", "ci-cd"],
        license_class=LicenseClass.MIT,
        adoption_state=AdoptionState.REFERENCE,
        subsystem="tool_gateway",
        notes="Inspired M7 worker governance review stages. No runtime dependency.",
        added_at="2026-05-24",
    ),
]
