"""Backend generator: auto-generate LiMa backend registry entries.

Takes discovered provider information and produces backend definition code
in LiMa's standard format, ready for insertion into backends_registry/.

CRITICAL: This tool GENERATES code suggestions but does NOT auto-modify
production registry files. Human review is required before merging.
"""

import logging
from textwrap import dedent

logger = logging.getLogger(__name__)


def _sanitize_name(name: str) -> str:
    """Convert a provider/model name to a LiMa-safe backend ID.

    Rules: lowercase, replace special chars with underscore, max 30 chars.
    """
    clean = name.lower().replace(" ", "_").replace("-", "_")
    clean = "".join(c for c in clean if c.isalnum() or c == "_")
    clean = clean.strip("_")
    return clean[:30]


def _estimate_timeout(models_count: int, has_reasoning: bool = False) -> int:
    """Estimate a reasonable timeout based on provider characteristics."""
    if has_reasoning:
        return 90
    if models_count > 20:
        return 60
    return 45


def generate_backend_entry(provider_info: dict) -> str:
    """Generate a LiMa backend entry from discovered provider info.

    Args:
        provider_info: dict with keys:
            - name: provider/model name
            - base_url: API endpoint URL
            - models: list of model IDs (optional)
            - fmt: 'openai' or 'anthropic' (default: 'openai')
            - requires_auth: bool (default: True)
            - auth_type: 'bearer' or 'api-key' (default: 'bearer')
            - env_key: env var name for API key (optional, auto-generated)
            - is_free: bool (default: False)
            - caps: list of capabilities (optional)
            - timeout: custom timeout (optional)

    Returns:
        String containing the backend entry code block.
    """
    name = _sanitize_name(provider_info.get("name", "unknown"))
    base_url = provider_info.get("base_url", "https://api.example.com/v1").rstrip("/")
    fmt = provider_info.get("fmt", "openai")
    requires_auth = provider_info.get("requires_auth", True)
    auth_type = provider_info.get("auth_type", "bearer")
    caps = provider_info.get("caps", ["tool_calls"])
    timeout = provider_info.get("timeout")
    models = provider_info.get("models", [])

    if not timeout:
        timeout = _estimate_timeout(len(models))

    # API key handling
    if requires_auth:
        env_key = provider_info.get("env_key", f"LIMA_{name.upper()}_API_KEY")
        key_source = f"os.environ.get('{env_key}', '')"
    else:
        key_source = "''"

    # Authentication style
    auth_field = ""
    if auth_type == "api-key" or auth_type == "x-api-key":
        auth_field = f",\n        'auth': 'x-api-key'"

    # Capabilities
    caps_str = ", ".join(f"'{c}'" for c in caps)

    # Primary model (first in list or generate from name)
    model = provider_info.get("model_id", models[0] if models else name)

    # Smart URL construction: avoid double /v1 and force chat completions path.
    if base_url.endswith("/v1"):
        chat_url = f"{base_url}/chat/completions"
    else:
        chat_url = f"{base_url}/v1/chat/completions"

    entry = dedent(f"""\
    '{name}': {{
        'url': '{chat_url}',
        'key': {key_source},
        'model': '{model}',
        'fmt': '{fmt}',
        'timeout': {timeout},{auth_field}
        'caps': [{caps_str}],
    }},""")

    return entry


def generate_registry_file(providers: list[dict], module_name: str = "discovered") -> str:
    """Generate a complete backends_registry/*.py file for multiple providers.

    Args:
        providers: List of provider_info dicts
        module_name: Name for the registry module file

    Returns:
        Complete file content as string.
    """
    lines = [
        f'"""Auto-discovered provider backends: {module_name}',
        "",
        "Generated by provider_probe pipeline.",
        '"""',
        "",
        "import os",
        "",
        "BACKENDS: dict[str, dict] = {",
    ]

    for info in providers:
        entry = generate_backend_entry(info)
        lines.append(entry)
        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def generate_constants_additions(provider_names: list[str]) -> str:
    """Generate the constants.py additions for GFW/CODE/TOOL sets.

    Args:
        provider_names: List of backend IDs to add

    Returns:
        String showing where to add each name in backends_constants.py
    """
    names_str = ", ".join(f"'{n}'" for n in provider_names)

    return dedent(f"""\
    # Add to GFW_BACKENDS in backends_constants.py:
    {names_str},

    # Add to CODE_CAPABLE_BACKENDS in backends_constants_code_tools.py (if coding verified):
    {names_str},

    # Add to TOOL_CAPABLE_BACKENDS in backends_constants_code_tools.py (if tool_calls supported):
    {names_str},
    """)
